build: 出力されたmjsの内部参照で拡張子を指定するようにアップデート
openameba/spindle pull request #1178
Opened 2024-11-20 12:22 UTC by yanagi0602

## 概要

packageが出力する成果物のmjsがspindle内部のモジュールを参照している時に、拡張子を省略しない対応を加えました。

## 経緯

ESMで開発しているプロジェクトでBreadcrumbListの利用を試みた所 `node_modules/@openameba/spindle-ui/Breadcrumb/BreadcrumbList.mjs` にある `import ChevronRightBold from '../Icon/ChevronRightBold';` が解決出来ないという問題が発生しました。
ESMでは相対参照において拡張子を省略しないことが期待されるので出力後のmjs内に存在する、相対参照を拡張子が省略されていない形へ置き換える対応を加えました。

## 目指すこと

dist配下に出力される成果物の内容の

```mjs
export { BreadcrumbItem, BreadcrumbList } from './Breadcrumb';
export { Button } from './Button';
import { ButtonGroup as Group } from '../ButtonGroup';
import ChevronRightBold from '../Icon/ChevronRightBold';
import ChevronRight from '../Icon/ChevronRight';
```

のようなimport/exportの参照が

```mjs
export { BreadcrumbItem, BreadcrumbList } from './Breadcrumb/index.mjs';
export { Button } from './Button/index.mjs';
import { ButtonGroup as Group } from '../ButtonGroup/index.mjs';
import ChevronRightBold from '../Icon/ChevronRightBold.mjs';
import ChevronRight from '../Icon/ChevronRight.mjs';
```

になっていること（内部参照以外はそのまま）

## 考えうる手段

他にもいくつか手段は考えたがrenamerでの置き換えは流石に無理が来た。という見方もできるものの、現状のtscでのbuildはメンテナンスコストが低く維持したいので、出力結果をreplaceする方針を採用

### 出力されたファイルのimportを置き換える（今回採用した手段）

- 良いところ
  - 現状のシンプルなbuildプロセスを維持できる
  - TypeScriptのアップデート等でESM出力に対応された場合等に消すだけで済む
- 良くない所
  - 解決方法がワークアラウンド的で複雑

### ESMの対応を辞めてcjsを読み込んでもらう

- 良いところ
  - renamerでのファイル変更だけでは不十分＝ESM対応を仕切れていない。と考えるとCJSのみ配布する形にしても良さそう
- 良くない所
  - ESM化に伴う恩恵を受けられなくなってしまう

### それぞれをpackageとして配布してexportsの設定を書く

- 良いところ
  - 現状のシンプルなbuildプロセスを維持できる
- 良くない所
  - 変更の規模が大きくなり、パッケージの配布方法自体に手を加える必要が出てくる。（破壊的変更になりそう）

### mjsの配布をrenamer利用のものではなくbuildのプロセス自体に手を加える

- 良いところ
  - 素直にbuild成果物をハイブリッドに出力できるようになる。
- 良くない所
  - buildプロセスのメンテナンスコストが高くなってしまう。

2024-11-20 12:23 UTC, yanagi0602 commented on bin/outputExtensionReplace.js
> +const { readdir, readFile, writeFile, stat, access } = require('fs').promises;
対象を `packages/*/dist` にしたいので、`root/bin` に設置しました。

2024-11-21 00:35 UTC, yanagi0602 commented
> ❌ > @openameba/spindle-syntax-themes:test

testがこれでコケてる＋他のrenovateのPRでも起きてるのでこちらは別で調査します。

2024-11-21 01:06 UTC, sasaplus1 reviewed
💬

2024-11-21 01:06 UTC, sasaplus1 commented on bin/outputExtensionReplace.js
> +        }
`Promise.allSettled`でいずれかが成功していたら〜という書き方はできそう

2024-11-21 01:06 UTC, sasaplus1 commented on bin/outputExtensionReplace.js
> +      /from\s+['"](\.\/|\.\.\/)(?!.*\.mjs['"])([^'"]+)(['"])/g;
意図しない文字列がマッチしたら怖いな〜

2024-11-21 01:06 UTC, sasaplus1 commented on bin/outputExtensionReplace.js
> + * 非同期の置換処理を行う関数
非同期の置換処理？

2024-11-21 01:13 UTC, yanagi0602 commented on bin/outputExtensionReplace.js
> +    const directories = await glob(join(__dirname, '../packages/*/dist'));
おわー、すみません。globを使わない書き方の時に利用してた部分をそのまま引継いじゃってました。
そちらでも良いので修正しました。

[refactor: getMjsFilesの削除](https://github.com/openameba/spindle/pull/1178/commits/ac3f5bc3d1ba44a254aad66ae2d0559f601630e4)

2024-11-21 01:21 UTC, yanagi0602 commented on bin/outputExtensionReplace.js
> + * 非同期の置換処理を行う関数
確かに言葉足らずかもですね…
文中の置き換え処理を並列で処理するための関数。的な意味で補足を残してました。

2024-11-21 01:22 UTC, yanagi0602 commented on bin/outputExtensionReplace.js
> +      /from\s+['"](\.\/|\.\.\/)(?!.*\.mjs['"])([^'"]+)(['"])/g;
そうですね。テストコードで担保すべき部分かなと考えてたのですが、こちらもう少しいい方法があれば変えたい所…

2024-11-21 02:13 UTC, sasaplus1 commented on bin/outputExtensionReplace.js
> +      /from\s+['"](\.\/|\.\.\/)(?!.*\.mjs['"])([^'"]+)(['"])/g;
確実にやりたいのならASTを扱うしか……しかし大掛かり感🤔 安心感もあるけど

2024-11-21 09:30 UTC, kc7891 commented on bin/outputExtensionReplace.js
> +      /from\s+['"](\.\/|\.\.\/)(?!.*\.mjs['"])([^'"]+)(['"])/g;
https://github.com/acornjs/acorn
ASTならこれとかですかね？ 🤔

2024-11-22 02:49 UTC, yanagi0602 commented on bin/outputExtensionReplace.js
> +        }
確かにですね。↓みたいな形で認識相違ないですか？👀

[refactor: try/catch部分をPromise.allSettledを利用した形に置き換え](https://github.com/openameba/spindle/pull/1178/commits/6f38a8586b00e25267e680084937781b67fdb866)

2024-11-22 02:51 UTC, yanagi0602 commented on bin/outputExtensionReplace.js
> +      /from\s+['"](\.\/|\.\.\/)(?!.*\.mjs['"])([^'"]+)(['"])/g;
ASTの話をされたので考えてみたのですが、結局accessしてresolveを返したら〜みたいなことを考えるとシンプルに使うだけだとダメかもですね…

最悪意図しない文字列がマッチしても対象のmjsの存在が保証されているので問題は起きづらい作りにはしたつもりですが、意図しない文字列がマッチしたら怖いよね。というのは拭えませんねｗ

2024-11-22 02:54 UTC, sasaplus1 commented on bin/outputExtensionReplace.js
> +      /from\s+['"](\.\/|\.\.\/)(?!.*\.mjs['"])([^'"]+)(['"])/g;
まあとりあえず正規表現にしときますか

2024-11-22 05:07 UTC, sasaplus1 commented on bin/outputExtensionReplace.js
> +        }
はい、ええと思います。以下のような書き方をするとifif〜というのが減っていいかなとは思います（雑に書いたのでそのまま使わないように）。

```diff
diff --git a/bin/outputExtensionReplace.js b/bin/outputExtensionReplace.js
index 4b059b3f..9cb6829e 100644
--- a/bin/outputExtensionReplace.js
+++ b/bin/outputExtensionReplace.js
@@ -38,23 +38,19 @@ async function replaceImportsInFile(filePath) {
         const importPath = resolve(dirname(filePath), p1 + p2);
         const mjsPath = importPath + '.mjs';
         const indexPath = join(importPath, 'index.mjs');
-        return await Promise.allSettled([
-          access(mjsPath),
-          access(indexPath),
-        ]).then((results) => {
-          const mjsPathResult = results[0];
-          const indexPathResult = results[1];
-          if (mjsPathResult.status === 'fulfilled') {
-            return `from '${p1}${p2}.mjs${p3}`;
-          } else if (indexPathResult.status === 'fulfilled') {
-            return `from '${p1}${p2}/index.mjs${p3}`;
-          } else {
-            console.error(
-              `.mjs または /index.mjs が存在しません: ${importPath}`,
-            );
-            process.exit(1);
-          }
-        });
+
+        const results = await Promise.allSettled([
+          access(mjsPath).then(() => `from '${p1}${p2}.mjs${p3}`),
+          access(indexPath).then(() => `from '${p1}${p2}/index.mjs${p3}`),
+        ]);
+
+        const res = results.find((r) => r.status === 'fulfilled');
+
+        if (!res) {
+          return Promise.reject();
+        }
+
+        return res.value;
       },
     );
     await writeFile(filePath, result, 'utf8');
```

2024-11-22 05:09 UTC, sasaplus1 commented on bin/outputExtensionReplace.js
> +            process.exit(1);
https://github.com/openameba/spindle/pull/1178/files#diff-56e82862a32a9e8213e3c73cf0e72f54a7fedbb006bf62406aeaecd21db8448eR76 をみると呼び出し元でprocess.exitしてるっぽいのに、ここでprocess.exitしちゃうと対象のファイルの一部の処理が中断されますな

2024-11-22 05:58 UTC, yanagi0602 commented on bin/outputExtensionReplace.js
> +            process.exit(1);
あー、たしかにです。ここは無視したい所なので余分ですね:pray:
```suggestion
```

2024-11-22 06:19 UTC, re-taro commented on bin/outputExtensionReplace.js
> +      /from\s+['"](\.\/|\.\.\/)(?!.*\.mjs['"])([^'"]+)(['"])/g;
@yanagi0602 

お疲れ様です〜。以下 AST (jscodeshift)使った例です。使えそうなら活用ください〜

```js
// bin/transformer.js
const { access } = require('fs').promises;
const { dirname, join, resolve } = require('path');

async function checkFileExists(filePath) {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

/**
 *
 * @param {import('jscodeshift').FileInfo} file
 * @param {import('jscodeshift').API} api
 */
module.exports = async function transformer(file, api) {
  const j = api.jscodeshift;
  const root = j(file.source);

  const importDeclarations = root.find(j.ImportDeclaration);

  await Promise.all(importDeclarations.nodes().map(async (node) => {
    const source = node.source.value;
    if (source.startsWith('./') || source.startsWith('../')) {
      const importPath = resolve(dirname(file.path), source);
      const mjsPath = `${importPath}.mjs`;
      const indexPath = join(importPath, 'index.mjs');

      const mjsExists = await checkFileExists(mjsPath);
      const indexExists = await checkFileExists(indexPath);

      if (mjsExists) {
        node.source.value = `${source}.mjs`;
      } else if (indexExists) {
        node.source.value = `${source}/index.mjs`;
      } else {
        console.error(`.mjs または /index.mjs が存在しません: ${importPath}`);
        process.exit(1);
      }
    }
  }));

  return root.toSource();
};
```

<details><summary>以下のように置換されています</summary>

```diff
diff --color=auto -r dist-old/Breadcrumb/BreadcrumbList.mjs dist-new/Breadcrumb/BreadcrumbList.mjs
2,3c2,3
< import ChevronRightBold from '../Icon/ChevronRightBold';
< import ChevronRight from '../Icon/ChevronRight';
---
> import ChevronRightBold from "../Icon/ChevronRightBold.mjs";
> import ChevronRight from "../Icon/ChevronRight.mjs";
diff --color=auto -r dist-old/Button/Button.figma.mjs dist-new/Button/Button.figma.mjs
2c2
< import { Button } from './Button';
---
> import { Button } from "./Button.mjs";
diff --color=auto -r dist-old/Dialog/Dialog.figma.mjs dist-new/Dialog/Dialog.figma.mjs
2c2
< import { Dialog } from './Dialog';
---
> import { Dialog } from "./Dialog.mjs";
diff --color=auto -r dist-old/Dialog/Dialog.mjs dist-new/Dialog/Dialog.mjs
3c3
< import { ButtonGroup as Group } from '../ButtonGroup';
---
> import { ButtonGroup as Group } from "../ButtonGroup/index.mjs";
diff --color=auto -r dist-old/Dialog/DialogExample.mjs dist-new/Dialog/DialogExample.mjs
3,5c3,5
< import { Button } from '../Button';
< import { SubtleButton } from '../SubtleButton';
< import { Dialog } from './Dialog';
---
> import { Button } from "../Button/index.mjs";
> import { SubtleButton } from "../SubtleButton/index.mjs";
> import { Dialog } from "./Dialog.mjs";
diff --color=auto -r dist-old/Form/Checkbox.figma.mjs dist-new/Form/Checkbox.figma.mjs
2c2
< import { Checkbox } from './Checkbox';
---
> import { Checkbox } from "./Checkbox.mjs";
diff --color=auto -r dist-old/Form/Checkbox.mjs dist-new/Form/Checkbox.mjs
2c2
< import { CheckBold } from '../Icon';
---
> import { CheckBold } from "../Icon/index.mjs";
diff --color=auto -r dist-old/Form/DropDown.mjs dist-new/Form/DropDown.mjs
3c3
< import { ChevronDownBold } from '../Icon';
---
> import { ChevronDownBold } from "../Icon/index.mjs";
diff --color=auto -r dist-old/Form/InlineDropDown.mjs dist-new/Form/InlineDropDown.mjs
3c3
< import { ChevronDownBold } from '../Icon';
---
> import { ChevronDownBold } from "../Icon/index.mjs";
diff --color=auto -r dist-old/Form/InvalidMessage.mjs dist-new/Form/InvalidMessage.mjs
2c2
< import { ExclamationmarkCircleFill } from '../Icon';
---
> import { ExclamationmarkCircleFill } from "../Icon/index.mjs";
diff --color=auto -r dist-old/Form/Radio.figma.mjs dist-new/Form/Radio.figma.mjs
2c2
< import { Radio } from './Radio';
---
> import { Radio } from "./Radio.mjs";
diff --color=auto -r dist-old/Form/Radio.mjs dist-new/Form/Radio.mjs
2c2
< import { CheckBold } from '../Icon';
---
> import { CheckBold } from "../Icon/index.mjs";
diff --color=auto -r dist-old/Form/ToggleSwitch.figma.mjs dist-new/Form/ToggleSwitch.figma.mjs
2c2
< import { ToggleSwitch } from './ToggleSwitch';
---
> import { ToggleSwitch } from "./ToggleSwitch.mjs";
diff --color=auto -r dist-old/HeroCarousel/HeroCarousel.mjs dist-new/HeroCarousel/HeroCarousel.mjs
3,7c3,7
< import ChevronLeftBold from '../Icon/ChevronLeftBold';
< import ChevronRightBold from '../Icon/ChevronRightBold';
< import Pause from '../Icon/Pause';
< import PlayFill from '../Icon/PlayFill';
< import HeroCarouselItem from './HeroCarouselItem';
---
> import ChevronLeftBold from "../Icon/ChevronLeftBold.mjs";
> import ChevronRightBold from "../Icon/ChevronRightBold.mjs";
> import Pause from "../Icon/Pause.mjs";
> import PlayFill from "../Icon/PlayFill.mjs";
> import HeroCarouselItem from "./HeroCarouselItem.mjs";
diff --color=auto -r dist-old/IconButton/IconButton.figma.mjs dist-new/IconButton/IconButton.figma.mjs
2c2
< import { IconButton } from './IconButton';
---
> import { IconButton } from "./IconButton.mjs";
diff --color=auto -r dist-old/InlineNotification/InlineNotification.figma.mjs dist-new/InlineNotification/InlineNotification.figma.mjs
2c2
< import { InlineNotification } from './InlineNotification';
---
> import { InlineNotification } from "./InlineNotification.mjs";
diff --color=auto -r dist-old/InlineNotification/InlineNotification.mjs dist-new/InlineNotification/InlineNotification.mjs
2,4c2,4
< import { Button as SpindleButton } from '../Button/Button';
< import { TextButton as SpindleTextButton } from '../TextButton/TextButton';
< import { IconButton as SpindleIconButton } from '../IconButton/IconButton';
---
> import { Button as SpindleButton } from "../Button/Button.mjs";
> import { TextButton as SpindleTextButton } from "../TextButton/TextButton.mjs";
> import { IconButton as SpindleIconButton } from "../IconButton/IconButton.mjs";
diff --color=auto -r dist-old/List/MoreLink.mjs dist-new/List/MoreLink.mjs
2c2
< import { ChevronRightBold } from '../Icon';
---
> import { ChevronRightBold } from "../Icon/index.mjs";
diff --color=auto -r dist-old/Modal/AppealModal.mjs dist-new/Modal/AppealModal.mjs
3,6c3,6
< import { ButtonGroup as Group } from '../ButtonGroup';
< import { CrossBold } from '../Icon';
< import { IconButton } from '../IconButton';
< import { SubtleButton } from '../SubtleButton';
---
> import { ButtonGroup as Group } from "../ButtonGroup/index.mjs";
> import { CrossBold } from "../Icon/index.mjs";
> import { IconButton } from "../IconButton/index.mjs";
> import { SubtleButton } from "../SubtleButton/index.mjs";
diff --color=auto -r dist-old/Modal/SemiModal.mjs dist-new/Modal/SemiModal.mjs
3,4c3,4
< import { CrossBold } from '../Icon';
< import { IconButton } from '../IconButton';
---
> import { CrossBold } from "../Icon/index.mjs";
> import { IconButton } from "../IconButton/index.mjs";
diff --color=auto -r dist-old/Pagination/Pagination.mjs dist-new/Pagination/Pagination.mjs
2,5c2,5
< import MenuHorizontal from '../Icon/MenuHorizontal';
< import PaginationItem from './PaginationItem';
< import { useShowItem } from './hooks/useShowItem';
< import { getLinkRelAttribute } from './helpers/getLinkRelAttribute';
---
> import MenuHorizontal from "../Icon/MenuHorizontal.mjs";
> import PaginationItem from "./PaginationItem.mjs";
> import { useShowItem } from "./hooks/useShowItem.mjs";
> import { getLinkRelAttribute } from "./helpers/getLinkRelAttribute.mjs";
diff --color=auto -r dist-old/Pagination/PaginationItem.mjs dist-new/Pagination/PaginationItem.mjs
2,7c2,7
< import ChevronRightBold from '../Icon/ChevronRightBold';
< import ChevronLeftBold from '../Icon/ChevronLeftBold';
< import TriangleendRightBold from '../Icon/TriangleendRightBold';
< import TriangleendLeftBold from '../Icon/TriangleendLeftBold';
< import { useItemPageNumber } from './hooks/useItemPageNumber';
< import { getLinkRelAttribute } from './helpers/getLinkRelAttribute';
---
> import ChevronRightBold from "../Icon/ChevronRightBold.mjs";
> import ChevronLeftBold from ".. [...]

2024-11-25 01:29 UTC, yanagi0602 commented on bin/outputExtensionReplace.js
> +      /from\s+['"](\.\/|\.\.\/)(?!.*\.mjs['"])([^'"]+)(['"])/g;
うおおおお！ありがとう。
可読性も高くてこちらのほうが良さそうだね…

exportにも対応する必要が有るのと、テストコードの修正が必要なのでこちら対応しようかと思いまする。

2024-11-25 02:52 UTC, yanagi0602 commented on bin/outputExtensionReplace.js
> +      /from\s+['"](\.\/|\.\.\/)(?!.*\.mjs['"])([^'"]+)(['"])/g;
`packages/*/dist/**/*.mjs` で dist直下の `*.mjs` 引っかかってない気がするな。

2024-11-25 03:22 UTC, yanagi0602 commented on bin/outputExtensionReplace.js
> +      /from\s+['"](\.\/|\.\.\/)(?!.*\.mjs['"])([^'"]+)(['"])/g;
`find packages/*/dist/** -iname '*.mjs' -print | xargs jscodeshift -t ./bin/outputExtensionReplace.js` にしてみる。

2024-11-25 04:12 UTC, sasaplus1 commented on bin/outputExtensionReplace.js
> +      /from\s+['"](\.\/|\.\.\/)(?!.*\.mjs['"])([^'"]+)(['"])/g;
```diff
-"postbuild": "jscodeshift -t ./bin/transformer.js packages/*/dist/**/*.mjs"
+"postbuild": "jscodeshift -t ./bin/transformer.js 'packages/*/dist/**/*.mjs'"
```

だとダメかな。実行するシェルがBashの場合globstarがonになってないと`**`は使えないと思うから。シングルクォートで囲む場合jscodeshiftがきちんと処理してくれないといけないけど。

2024-11-25 04:24 UTC, yanagi0602 commented on bin/outputExtensionReplace.js
> +      /from\s+['"](\.\/|\.\.\/)(?!.*\.mjs['"])([^'"]+)(['"])/g;
> 実行するシェルがBashの場合globstarがonになってないと**は使えないと思う

なるほど、実行環境に依存するんですね？👀

> Skipping path packages/*/dist/**/*.mjs which does not exist. 

とのことで

> jscodeshiftがきちんと処理してくれないといけないけど。

はしてくれなさそうな気がしますなぁ。

2024-11-25 04:25 UTC, sasaplus1 commented on bin/outputExtensionReplace.js
> +      /from\s+['"](\.\/|\.\.\/)(?!.*\.mjs['"])([^'"]+)(['"])/g;
```diff
-find packages/*/dist/** -iname '*.mjs' -print
+find packages/*/dist -iname '*.mjs' -print
```

かな、`-type f`もつけると確実そうだけどディレクトリに拡張子つけるとも思えんしいいか

2024-11-25 04:28 UTC, yanagi0602 commented on bin/outputExtensionReplace.js
> +      /from\s+['"](\.\/|\.\.\/)(?!.*\.mjs['"])([^'"]+)(['"])/g;
あ、確かに `/**` は余分ですな。失礼しました。
`dir.mjs` みたいなディレクトリを対象にしたい意図は無いので `-type f` もつけちゃいます。

2024-11-25 04:47 UTC, yanagi0602 commented
@sasaplus1 @kc7891 @re-taro 

りんたろーくんの提案を採用させてもらいまして、以下のcommitで対応しました。
[feat: jscodeshiftを利用した置き換えに修正](https://github.com/openameba/spindle/pull/1178/commits/2131f7f55c28a1427c5dff298c75a84c098b6428)

- exportsにも対応
- テストコードのアップデート（モックする必要が有るものが減ってとってもハッピーですね！）
  - 置き換え部分を検査するとjscodeshiftのテストになりそうなので、テストする範囲を置き換え対象のチェックに閉じました。
  - checkFileExistsのテストを追加
- 対象ファイルからdist直下のmjsが漏れてたので実行コマンドのアップデート

2024-11-25 04:49 UTC, yanagi0602 commented
（操作対象も出力したほうが良いですね。対応します。）

2024-11-25 05:08 UTC, sasaplus1 commented
2131f7f55c28a1427c5dff298c75a84c098b6428 を`$ git commit --amend --author="re-taro <~email~>"`でコミットするのがﾖｻｿｳ

2024-11-25 06:27 UTC, yanagi0602 commented
https://github.com/openameba/spindle/pull/1178#issuecomment-2496863745
あ、この手がありましたか。Slackで別途相談してたんですがそれで良さげなのでそうしました:spindler:

2024-11-25 07:44 UTC, yanagi0602 commented on bin/outputExtensionReplace.js
> +      /from\s+['"](\.\/|\.\.\/)(?!.*\.mjs['"])([^'"]+)(['"])/g;
`jscodeshift -t ./bin/outputExtensionReplace.js packages/*/dist/** --extensions=mjs` で良いことに気が付きました。

> --extensions=EXT transform files with these file extensions (comma separated list) (default: js)

2024-11-26 09:33 UTC, kc7891 commented on bin/outputExtensionReplace.js
> +          }
ファイルの存在チェック、コスト高そうなイメージなので必要に応じてでも良いかも？
```suggestion
          const mjsExists = await checkFileExists(mjsPath);
          if (mjsExists) {
            node.source.value = `${value}.mjs`;
            return;
          }

          const indexExists = await checkFileExists(indexPath);
          if (indexExists) {
            node.source.value = `${value}/index.mjs`;
            return;
          }

          console.error(
              `missing ${mjsPath} and ${indexPath} for ${file.path}`,
          );
          return;
```

2024-11-27 00:58 UTC, yanagi0602 commented on bin/outputExtensionReplace.js
> +          }
@kc7891 
たしかにですね。以下のように変更加えることで、 `mjsPath` が存在したときは叩かなくなったかと思いますがいかがでしょうか👀

[refactor: checkFileExistsのタイミングを変更](https://github.com/openameba/spindle/pull/1178/commits/6e2adbd5d5065e092ecb046a07893c0200d62944)

2024-11-27 03:01 UTC, kc7891 approved these changes
👍

2024-11-29 06:36 UTC, sasaplus1 approved these changes
🚀

2024-11-29 06:43 UTC, sasaplus1 requested changes
💭

2024-11-29 06:43 UTC, sasaplus1 commented on .eslintrc.json
> +    "@typescript-eslint/no-var-requires": "off"
https://typescript-eslint.io/rules/no-var-requires/

deprecated?

2024-11-29 06:43 UTC, sasaplus1 commented on bin/outputExtensionReplace.test.js
> +    ].forEach(({ value, expected }) => {
it.eachの方がどれか1つが失敗しても全部実行されるし、どれがこけたかわかりやすいからそちらを使った方が良さそう

2024-11-29 06:43 UTC, sasaplus1 commented on .eslintrc.json
> +    "@typescript-eslint/no-var-requires": "off"
できたらoverridesで適用したいファイルを絞ってruleを適用した方が良いのかなとも思いました

2024-12-02 02:39 UTC, yanagi0602 commented on bin/outputExtensionReplace.test.js
> +    ].forEach(({ value, expected }) => {
たしかにですね。こちらで対応しました。
[test: test.eachを利用したテスト方法へ変更](https://github.com/openameba/spindle/pull/1178/commits/399c06d50bec70448bbc4aa8b12993a7edc323df)

2024-12-02 02:41 UTC, sasaplus1 approved these changes

2024-12-02 02:41 UTC, yanagi0602 commented on .eslintrc.json
> +    "@typescript-eslint/no-var-requires": "off"
deprecatedなのは8系からですかね？バージョンが上げるタイミングで置き換えで良きかなと思いました。

overrides検討してみたんですが、 `.js` の拡張子が cjs なのか mjs なのかの区別が出来ないので、利用箇所で消すことにしました:pray:
[chore: lintのルールをアップデート](https://github.com/openameba/spindle/pull/1178/commits/5a4dcc1b92252a50e98b3c1a753f00f8e57da754)

2024-12-02 02:42 UTC, sasaplus1 commented on .eslintrc.json
> +    "@typescript-eslint/no-var-requires": "off"
なるほど

2024-12-02 06:34 UTC, sasaplus1 approved these changes

2024-12-03 06:18 UTC, merged