HeroCarouselを追加
openameba/spindle pull request #348
Opened 2022-02-16 11:30 UTC by itsminadesu

# 概要
HeroCarouselコンポーネントを追加しました

<img width="1056" alt="スクリーンショット 2022-02-16 20 02 35" src="https://user-images.githubusercontent.com/42470015/154251949-ea9bb795-bf20-48e1-a63c-08d8a0f206cd.png">

最近Ameba Newsで作られたカルーセルが最も最新かつアクセシビリティ要件も考慮されたものだったので、そちらの実装を(基本的には)丸っと持ってきています

## Props
HeroCarouselに渡せるPropsは以下です
- [必須]`carouselList`(array)
    - [必須]`imageUrl`(string)
    - [必須]`link`(string)
    - [必須]`title`(string): 18文字までは表示 / 19文字以降は省略
- [任意]`classnames`(string): カルーセル全体を囲むclass名

カルーセルの再生速度や自動再生の有無なども渡せるようにしようか迷ったものの、今Amebaで実装されているカルーセルは全て同じ要件(4000msかつ自動再生)だったので、一旦は固定値にします(もし今後秒数を変えたり自動再生辞めたいなどの要件が出てきたら、その時に対応する形で良いかなと！)

# 関連リンク
諸々の都合上関連リンクを貼れないため、このPRの作成通知が流れるSlackのスレに貼ります 🙏🏻

2022-02-16 12:00 UTC, herablog commented
Storybookの素材がw

2022-02-16 12:47 UTC, takami-shunsuke reviewed
細かいですが気になったところを挙げてみました🙏

2022-02-16 12:47 UTC, takami-shunsuke commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.tsx
> +              src={`${carouselItem.imageUrl}?size=640`}
```suggestion
              src={`${carouselItem.imageUrl}`}
```
[nits] ここのクエリパラメータはCDN依存の値のため汎用コンポーネントとしては削除した方が良さそうです！

2022-02-16 12:47 UTC, takami-shunsuke commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.tsx
> +};
[Q] TS で書かれているため、静的型は担保されているのとバンドルサイズを若干削減できるため、`propTypes`はなくても良いかなと思いました。もしくは実行時にも型エラーを検出したいなどのモチベーションでしょうか？👀（`HeroCarouselItem.tsx`も同様で！）

2022-02-16 12:47 UTC, takami-shunsuke commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.tsx
> +export const HeroCarousel: FC<Props> = React.memo(function AutoPlayCarousel({
```suggestion
export const HeroCarousel: FC<Props> = React.memo(function HeroCarousel({
```
[nits] 細かいのですがここの命名も揃えられると良さげです！

2022-02-16 12:47 UTC, takami-shunsuke commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.tsx
> +  className?: string;
[Q] Spindle UI の思想としてメインのコンポーネントは `className` を Props で受け取らないような気がしたため、今回は除いた方が良いかも？です！

2022-02-17 01:04 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.tsx
> +  className?: string;
確かにそうですね、、！消しました！ -> https://github.com/openameba/spindle/pull/348/commits/12740591e06214a864c2e867ef5c842c24d96c4e

2022-02-17 01:04 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.tsx
> +export const HeroCarousel: FC<Props> = React.memo(function AutoPlayCarousel({
揃えました！ -> https://github.com/openameba/spindle/pull/348/commits/4c4abf09ad581df71a9db611812fb1b39aef21f4

2022-02-17 01:04 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.tsx
> +              src={`${carouselItem.imageUrl}?size=640`}
消しました！ -> https://github.com/openameba/spindle/pull/348/commits/a76648feebc91efdeb86d4d2fa41097418e60e47

2022-02-17 01:05 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.tsx
> +};
最初PropTypesなしで実装 → localの`yarn test`も問題なし → PR出す → CIが`xxx is missing in props validation     react/prop-types`でコケるというムーブがあり、なるほど 🤔 と思いつけた次第です 🙇🏻 
https://github.com/openameba/spindle/runs/5212856017?check_suite_focus=true

2022-02-17 01:32 UTC, takami-shunsuke reviewed
こちらも確認お願いしたいです🙏

2022-02-17 01:32 UTC, takami-shunsuke commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
> +  overflow: hidden;
```suggestion
  overflow: hidden;
  padding: 1px 0;
  margin: -1px 0;
```
[nits] 上下のアウトラインが削れてしまっているので、例えばここでスペースを確保するなどすると良さそうです！（いくつか対応パターンはありそうです）

before | after
-- | --
<img width="343" alt="" src="https://user-images.githubusercontent.com/92707228/154386720-55a16496-e38f-43d7-b5af-797e1544533f.png"> | <img width="346" alt="" src="https://user-images.githubusercontent.com/92707228/154386711-b11d0638-79e1-4d64-b87d-d278958d9a81.png">

2022-02-17 01:32 UTC, takami-shunsuke commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.tsx
> +            <img
[nits] 画面外にも渡るコンテンツなので、`loading="lazy"`をつけてあげると良さそうです！

2022-02-17 01:48 UTC, takami-shunsuke commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.tsx
> +};
なるほどです！確かに ESLint のルールが効いてそうでした
今までネストしたコンポーネントは存在しなかったため問題なかった形ですね👀

[IMO]
今後も TS で書かれていくと思うため `packages/spindle-ui/src/.eslintrc.json` などを作成して
以下のルールを追加し、`propTypes` は削除してしまっても良さげと思いました
```json
"react/prop-types": "off"
```

2022-02-17 02:29 UTC, keiya01 commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.tsx
> +            <img
これ個人的にはつけない方が良さそうと思っています:eyes:
Heroなのでトップの目立つところに置かれるはずで、そうなるとLCP判定になりやすく、lazyをつけているとLCPが遅くなる可能性があるかなと思いました！

2022-02-17 02:30 UTC, keiya01 commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.tsx
> +            <img
初期表示で隠れる部分だけlazyにできると良さそうですがそれは難しそう、、

2022-02-17 02:33 UTC, keiya01 commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.tsx
> +const ITEM_LINK_CLASS_NAME = 'js-auto-play-carousel-item-link';
[nits]
できれば宣言的に書きたいですが別対応でも良さそうです:eyes:
ref: slackのコメント参照

2022-02-17 02:34 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
> +  overflow: hidden;
:nanto_: 
修正しました！ -> https://github.com/openameba/spindle/pull/348/commits/d0c72b51d0da8dc85412cfa5495dca5df75361a9

![スクリーンショット 2022-02-17 11 34 30](https://user-images.githubusercontent.com/42470015/154393701-e6e3941c-fdf4-4fb5-b255-4daaf08aeb64.png)

2022-02-17 02:35 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.tsx
> +};
:naruhodo:

削除 & 設定を追加しました！ -> https://github.com/openameba/spindle/pull/348/commits/57ec56c0156edc5e2a85163d6f961462aab3d940

2022-02-17 02:36 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.tsx
> +            <img
:tashikani:
つけました！:performance: :takamin:  -> https://github.com/openameba/spindle/pull/348/commits/3f55fe42f7e530f5324780e209a3c6d79a22db0a

2022-02-17 02:47 UTC, herablog commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.tsx
> +            <img
こりね〜 カルーセルの`loading="lazy"` に関しては閾値的におそらくほぼ判定内に収まっちゃう問題もありますな。[Priority Hints](https://wicg.github.io/priority-hints/)ユースケースの一つかなと思いつつ現状は...!

2022-02-17 02:50 UTC, keiya01 commented on packages/spindle-ui/src/HeroCarousel/hooks/useAutoPlayCarousel.ts
> +  const slideToNext = (ignoreHover = false) => {
[nits]
この辺の関数を`useCallback`で囲っておいても良さそうと思いました:eyes:
[使用側](https://github.com/openameba/spindle/pull/348/files#diff-930d3e8cb750e738cc267798ba2e07e6374ed0885e192fdcca0a05c29bd12e72R36)では現状はComponentに切り分けられていないですが、後々Componentに切り分けた時にメモ化されていない関数を渡すことで無駄な再レンダリングの原因になりそうなのでとりあえず囲っておいても良さそうかなと思いました！

2022-02-17 02:50 UTC, keiya01 commented on packages/spindle-ui/src/HeroCarousel/hooks/useAutoSlide.ts
> +  const activateAutoSlide = () => {
ここもuseCallbackで囲って良さそうですかね:eyes:

2022-02-17 02:50 UTC, keiya01 commented on packages/spindle-ui/src/HeroCarousel/hooks/useSliderMoveEvent.ts
> +  const onMouseMove = (e: MouseEvent) => {
ここもuseCallbackで囲って良さそう:eyes:

2022-02-17 02:50 UTC, keiya01 commented on packages/spindle-ui/src/HeroCarousel/hooks/useSliderTransition.ts
> +  const handleTransitionEnd = () => {
ここもuseCallbackで囲って良さそう:eyes:

2022-02-17 02:50 UTC, keiya01 commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.stories.mdx
> +export const carouselList = [
[Q]
少し気になったのですがアイテムが0のケースや1つだけ(左右に移動しない)のケースも考慮しておいた方が良さそうでしょうか:eyes:

2022-02-17 02:52 UTC, herablog commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.stories.mdx
> +![stability-experiment](https://img.shields.io/badge/stability-experiment-red.svg)
ステータス設定ありがとうございます。本番利用できる(してる)コンポーネントなので`stable`か少し心配なら`unstable`でいってみようかなと思っております！

https://github.com/openameba/spindle/tree/main/packages/spindle-ui#%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88%E4%B8%80%E8%A6%A7

2022-02-17 02:59 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.stories.mdx
> +export const carouselList = [
これ迷ったんですよねええ
現状は、カルーセル使おうとしているぐらいなんだから最低2つはあってくれというお気持ち実装になっています 😇

2022-02-17 03:04 UTC, takami-shunsuke commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.tsx
> +            <img
諸々確かにです…！今回はなしで良さそうです🙇‍♂️

2022-02-17 03:23 UTC, keiya01 commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.stories.mdx
> +export const carouselList = [
なるほど！それであれば[storybookのdescription](https://github.com/openameba/spindle/pull/348/files#diff-839daad9cbd985fc4bd3453b8bb233935a1ce603b213d5057b07d53237aa4384R74-R76)に意図している使われ方を書いておくと良さそうかなと思いました:eyes:

2022-02-17 03:24 UTC, herablog commented
@itsminadesu ちなみにこり、いつまでに出したいかありますかな！？

2022-02-17 03:33 UTC, itsminadesu commented
@herablog 
> ちなみにこり、いつまでに出したいかありますかな！？

このカルーセルは今やってる施策([投稿トレンドページ](https://content.ameba.jp/trend_post/index.html)のフルリニューアル)で使用するためSpindle Component化したのですが、投稿トレンドのスケジュールが以下のようになっているため、来週月曜に出せたら非常に嬉しいなと思っています！ 🙏🏻 
 
```
今週: HeroCarouselの実装
来週月曜: HeroCarouselリリース(できたら嬉しい)
来週火曜: HeroCarouselを投稿トレンドページで呼び出す
来週水曜: 祝日
来週木曜: 投稿トレンドのQC
```
ただ今別件で投稿トレンド実装が待ちの状態になっており、実際は2, 3日スケジュールが押す事になると思うのでMUSTではないです！ 🙏🏻

2022-02-17 03:33 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.stories.mdx
> +export const carouselList = [
:tashikani:
天才だね

2022-02-17 03:37 UTC, herablog commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.stories.mdx
> +export const carouselList = [
0の場合は表示されない想定にはなっているのかな..!? (lodashじゃなくても良さそうだけど)

https://github.com/openameba/spindle/blob/57ec56c0156edc5e2a85163d6f961462aab3d940/packages/spindle-ui/src/HeroCarousel/HeroCarousel.tsx#L41-L43

2022-02-17 03:50 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.stories.mdx
> +export const carouselList = [
あ、たしかにそうでした、、！ 🙇🏻 
というのと、基本的には5個はある想定で組まれてることを思い出しまして、そちらも明記しておきます 🙏🏻 

https://github.com/openameba/spindle/blob/57ec56c0156edc5e2a85163d6f961462aab3d940/packages/spindle-ui/src/HeroCarousel/hooks/useAutoPlayCarousel.ts#L13

2022-02-17 05:42 UTC, herablog commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.tsx
> +      <section
ここの意味付けは利用側で決めてもいいかなと思ったけど、HEROで意味つけてるのでいいかもしれないなぁ。

sectionにする場合、[見出しなしのパターン](https://developer.mozilla.org/ja/docs/Web/HTML/Element/section#using_a_section_without_a_heading)でもいけそうだけど、付けられるようにしてもいいかもしれない？ AmebaNewsの実装例 cc @tokimari @syasuda90 
<img width="504" alt="Ameba Newsのソースコード" src="https://user-images.githubusercontent.com/869023/154412606-3c0432f5-3b71-4aad-b906-8da6030eb955.png">

2022-02-17 06:17 UTC, herablog commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.tsx
> +  if (isEmpty(carouselList)) {
依存モジュールできるだけ減らしたいので、ここはlodashじゃなく件数確認にしたいです！あと20行目で先に確認しちゃってもいいかも？もしくはこの方針通り今はスルーもあるかもしれない。
https://github.com/openameba/spindle/pull/348/files#r808628383

2022-02-17 06:20 UTC, herablog commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.tsx
> +          onClick={handleLinkClick}
Q: ちなみに今回の用件ではアイテム選択時に何かしら利用側から処理を加えたい場合はありますかな？なければこのまま進めて、Newsでは必要そうなので別途改修して良さそうです〜

2022-02-17 06:25 UTC, herablog commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.tsx
> +    isEqual(prevProps.carouselItem, nextProps.carouselItem),
こちらもできるだけ依存モジュール増やさないようにlodash使わないようにしたいかもです！少し面倒だけどこのコンポネートだとプロパティそれぞれ比較でも良さげさん。

2022-02-17 06:29 UTC, herablog commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
> +/* stylelint-disable plugin/selector-bem-pattern */
この`stylelint-disable` ファイル全体じゃなく必要な箇所だけにするか命名を調整してもらって良いでしょか！Toastの命名が参考になりそうっす！
https://github.com/openameba/spindle/blob/main/packages/spindle-ui/src/Toast/Toast.css

2022-02-17 06:45 UTC, herablog commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.stories.mdx
> +      'https://images.microcms-assets.io/assets/24995dc41d5c40808fe4a9e3f6fb2b20/eb868ea0d6af41aaaff3091b7c1d4cfb/team_article_002_cover.png?w=2736&h=1208&fm=avif&q=90',
いい画像の設定、非常にありがたいです！ただ画像が必要さに対して綺麗すぎるので以下のような対応を検討お願いしたいですw

- `fm=avif`を`fm=webp`に まだAVIFサポート少ないため
- `q=90`を`q=85` これくらいで十分では？と思いますが画質悪すぎたら教えてください
-  `w=2736&h=1208` 表示領域に対して2倍くらいの数値にしてもらえますでしょか

2022-02-17 06:53 UTC, keiya01 commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
> +@media (prefers-reduced-motion) {
```suggestion
@media (prefers-reduced-motion: reduce) {
```
明示的にする方に合わせてたのを思い出しました
https://github.com/openameba/spindle/pull/242#discussion_r668585195

2022-02-17 06:56 UTC, tokimari reviewed
めちゃくちゃチョッパヤ対応ありがとうございます！ 👍 👍 👍 

nits. focus時のアウトラインを、spindleで定義している `--color-focus-clarity` を使うようにした方が、spindle-ui内で統一感がでて良さそうかなと思いました！
ref: http://localhost:6006/?path=/story/button--large

2022-02-17 06:56 UTC, tokimari commented on packages/spindle-ui/src/HeroCarousel/hooks/useAutoPlayCarousel.ts
> +    document.body.addEventListener('touchend', onTouchEnd);
q. document.bodyにイベント貼っちゃうのが気になりましたが、 `onMouseUp`, `onTouchEnd` も他のhandlerと同様にHeroCarousel.tsxの要素にbindするのではダメなのですっけ・・！

2022-02-17 06:56 UTC, tokimari commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.css
> +  font-size: 15px;
must. spindle-uiは文字サイズ指定emで統一していたかと思います:pray:
ref: https://a11y-guidelines.ameba.design/1/4/4/

2022-02-17 06:56 UTC, tokimari commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.stories.mdx
> +    title: '生きたコンテンツをつむぐ',
comment. loopになっている＋前後にコピーされたスライドがいて、正しいフォーカス順になっているのかわかりづらかったので（w）、titleの先頭に1,2,3・・みたいに仮のナンバリングしてもらっても良いでしょうか・・w機能にはなんの影響もないんですが:innocent:

2022-02-17 06:56 UTC, tokimari commented on packages/spindle-ui/src/HeroCarousel/hooks/useSliderTransition.ts
> +    }
キー操作で次へ、前へボタンを押下してスライドを移動した時、移動先のスライドにfocusして欲しいのですが、どうもここの `disableAutoFocus` がtrueになってしまいfocusされないようです 🤔 

Notionのアクセシビリティ要件の
> [実装]自動再生をオフにしている時に、スライドの変更をアナウンスする

にあたるのですが、確認お願いします〜！
（ライブリージョンを実装しなくても、focusすることでスライドの変更を伝えることができるため）

2022-02-17 06:56 UTC, tokimari commented on packages/spindle-ui/src/HeroCarousel/hooks/useSliderTransition.ts
> +    }
newsではfocusされる、ameblo.jpトップではfocusされないようでした。（今回は実装的には後者を参考にしているのかな）

2022-02-17 06:56 UTC, tokimari commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.css
> +    width: 320px;
q. Itemの画像の縦横比が固定になってると思いますが、奇跡的に全ての案件で同じ比率だったのでしょうか。
今後拡張したくなったら拡張できるでいいと思いつつ、質問ですw

2022-02-17 06:56 UTC, tokimari commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
> +  width: 18px;
imo. こちらもem指定にしておくと、文字サイズ変更時にボタンも大きくなり視認性が向上しそうです 💪 
https://a11y-guidelines.ameba.design/1/4/4/

2022-02-17 06:56 UTC, tokimari commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
> +  width: 18px;
nits. nth-of-type でのpadding調整の件も踏まえて
- svgをwidth, height: 1.5emくらいにする＋ `vertical-align: middle;` で上下中央寄せにする
- buttonに`text-align:center;` を当ててsvgをセンタリングする
- prevのsvg, nextのsvgを `margin-left: 0.1em` とかで微調整する

のように、相対位置でCSS指定すると、文字サイズを反映しつついい感じの位置に調整できるかも！？と妄想しました 😄 
（アクセシビリティの範疇では、あくまで「文字サイズ拡大しても情報が欠けずに拡大できればok」で、このコメントは「文字拡大してもスタイリングをいい感じにするため」という温度感なのでnitsです）

2022-02-17 06:56 UTC, tokimari commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.stories.mdx
> +  carouselListはlink, imageUrl, titleの3つからなります。titleは19文字以上の場合、三点リーダーで省略されます
comment. http://localhost:6006/?path=/docs/toast--normal#%E3%81%93%E3%81%AE%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88%E3%81%A7%E3%82%84%E3%81%A3%E3%81%A6%E3%81%84%E3%82%8B%E3%81%93%E3%81%A8 の例のように、HeroCarouselでやっていること、注意点が記載してあると利用時に安心かなと思いました 😄

2022-02-17 06:56 UTC, tokimari commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.stories.mdx
> +<HeroCarousel carouselList={carouselList} />
nits. コード見ればわかるんですが、carouselListの想定する型がどこかに明記されていてもいいかも・・！？

2022-02-17 07:09 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.tsx
> +          onClick={handleLinkClick}
今回は特になしです！

2022-02-17 07:16 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.css
> +    width: 320px;
奇跡的にと言いますか、カルーセル案件来るたびに過去のカルーセルの実装を持ってきてるっぽいので常に一緒なんだと思います！

2022-02-17 07:17 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.css
> +    width: 320px;
直近実装された(る)3つが全部同じサイズなので、今後拡張したくなったらその時に対応で良いかと個人的には思っております

2022-02-17 07:20 UTC, herablog commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.tsx
> +            <img
loading="lazy"は有用な時も多々あるので、ご指摘ありがとうございます！

2022-02-17 07:41 UTC, herablog commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.css
> +    width: 320px;
既存プロジェクトで実際に利用する際にいくつか追加用件ありそうなので、別でやりましょか。(その時にchildrenでもアイテム渡せるようにするかも)

なのでステータスはwork in progressでいきましょか！
ref: https://github.com/openameba/spindle/pull/348#discussion_r808625454

2022-02-17 07:49 UTC, herablog commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.stories.mdx
> +![stability-experiment](https://img.shields.io/badge/stability-experiment-red.svg)
WIP!

https://github.com/openameba/spindle/pull/348#discussion_r808751604

2022-02-17 11:22 UTC, herablog commented
@itsminadesu そしたら今回のリリースまでに以下だけ対応お願いして良いでしょか！

- :lodash_: 読み込まない
- コンポーネントステータスをWIP!にする

それ以外は持ち越しても大丈夫そうな気がする！

2022-02-18 01:17 UTC, itsminadesu commented
@tokimari 
> nits. focus時のアウトラインを、spindleで定義している --color-focus-clarity を使うようにした方が、spindle-ui内で統一感がでて良さそうかなと思いました！

他コンポーネントに合わせました！ -> https://github.com/openameba/spindle/pull/348/commits/da6d281e185599b6818c569544d21ee686ec26de

![スクリーンショット 2022-02-18 10 16 40](https://user-images.githubusercontent.com/42470015/154598906-dc285bb2-c68c-46db-9bc7-4b56a82a552e.png)

2022-02-18 01:17 UTC, itsminadesu commented
@herablog @tokimari @takami-shunsuke @keiya01 

皆様方〜！！レビューありがとうございます！！！ 💯 

大変今更ですが、本PRに至るまでの背景とゴールについて共有していなかったことに気づきまして、共有です！ 🙇🏻 

-----

弊チームのとある施策内でカルーセルが用いられる画面の実装があるのですが、カルーセルは今まで通り各リポジトリで実装される予定でした
ただ、「せっかくならこのタイミングでSpindle化もやりたいね〜」という話が施策の開発が始まってから出た関係で、リリーススケジュールは変わらないまま+Spindleの開発となっています 🙏🏻 
そのため本施策の期間内で「カルーセルが使われている既存ページの要件を全て満たす実装」をするのは時間的に厳しく、本PRのゴールは「今回の施策で必要十分使える &  今回の施策内容に依存しないカルーセルの実装」とさせていただきたいです！

> 今回の施策で必要十分使える
幸い、既に実運用されているAmebaNewsのカルーセルが要件を満たしていたため、本PRでは基本的にそちらの実装を持ってきています！

-----

頂いたレビューの8, 9割型はサクッと修正できそうだったので対応しましたが、
- (一部の)既存コードのリファクタ
- 本施策のカルーセルでは必要ない要件

は本PRでは対応せず、別PRでの対応とさせていただきたいです！ 🙏🏻 
https://github.com/openameba/spindle/issues/349

一部の対応は後回しになりますが、本施策の期間外で細々とPR送っていければと思いますので、他に気になる点・追加要件等ありましたらIssueに追記していただけると嬉しいです！！！

2022-02-18 01:18 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.stories.mdx
> +<HeroCarousel carouselList={carouselList} />
以下2点の理由から、このままで良いかなと思っています！ 🙏🏻 
- carouselListの中身は`<Description>`の中に記載してある
- 命名からstringであることは容易に判断できる

2022-02-18 01:18 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.stories.mdx
> +  carouselListはlink, imageUrl, titleの3つからなります。titleは19文字以上の場合、三点リーダーで省略されます
(HeroCarouselの最終形態としてはもう少し書きたい内容はあるものの、一旦は現時点での実装で確定しているものだけ)記載しました！ -> https://github.com/openameba/spindle/pull/348/commits/87ab6f1640ee41489d9b9f94efd83023fa3d867d

2022-02-18 01:19 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
> +  width: 18px;
全体的にemにしつつ、文字を「極大」にしたときにボタン等も大きくなりつつレイアウトが崩れないように調整しました！ -> https://github.com/openameba/spindle/pull/348/commits/5ab9465ed684b8debb60fe1f99945ae94be6447a
![スクリーンショット 2022-02-18 9 55 09](https://user-images.githubusercontent.com/42470015/154598763-7cbf066b-ae79-4021-82b7-89bdb3ca8760.png), https://github.com/openameba/spindle/pull/348/commits/1482ea21814106fa5b2a61c310c629340641eb5f

2022-02-18 01:20 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
> +  width: 18px;
👆 わかりにくいですが、文字が「極大」の時のスクショです

2022-02-18 01:20 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.css
> +    width: 320px;
WIPにしました！ 🙏🏻

2022-02-18 01:20 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.stories.mdx
> +    title: '生きたコンテンツをつむぐ',
ナンバリング追加しました〜！ -> https://github.com/openameba/spindle/pull/348/commits/87ab6f1640ee41489d9b9f94efd83023fa3d867d

2022-02-18 01:20 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.css
> +  font-size: 15px;
font-sizeをemにしつつ、文字を「極大」にしてもレイアウトが崩れないように調整しました！ -> https://github.com/openameba/spindle/pull/348/commits/5ab9465ed684b8debb60fe1f99945ae94be6447a
![スクリーンショット 2022-02-18 9 55 09](https://user-images.githubusercontent.com/42470015/154598763-7cbf066b-ae79-4021-82b7-89bdb3ca8760.png)

2022-02-18 01:21 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.tsx
> +          aria-label="1つ後ろのアイテムに移動"
個人的には「後ろの」でも「後の」でも特に違和感ないので、このままで行きます！🙏🏻

2022-02-18 01:21 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
> +}
:tashikani:
修正しました！ -> https://github.com/openameba/spindle/pull/348/commits/bd182a838957b2dd3d22816c157662e8e2c2c1dd

2022-02-18 01:21 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
> +@media (prefers-reduced-motion) {
`reduce`付けましました！ 💯

2022-02-18 01:21 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.stories.mdx
> +      'https://images.microcms-assets.io/assets/24995dc41d5c40808fe4a9e3f6fb2b20/eb868ea0d6af41aaaff3091b7c1d4cfb/team_article_002_cover.png?w=2736&h=1208&fm=avif&q=90',
> いい画像の設定

😄 

こちらで対応しました！ -> https://github.com/openameba/spindle/pull/348/commits/87ab6f1640ee41489d9b9f94efd83023fa3d867d

2022-02-18 01:21 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
> +/* stylelint-disable plugin/selector-bem-pattern */
命名を変更しました！ -> https://github.com/openameba/spindle/pull/348/commits/c193ea822f1a5c6a3044d0b8295bd0ac33ffaee0

2022-02-18 01:21 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.tsx
> +  if (isEmpty(carouselList)) {
他の箇所含め、HeroCarouselではlodash使わないように修正しました！ -> https://github.com/openameba/spindle/pull/348/commits/64d789f5c58d9643e10d5d87e935091b54549605

2022-02-18 01:21 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.tsx
> +      <section
sectionをHeroCarouselの内部に配置するか、利用側に配置するかのどちらかですよね... 👀 

:nayamiku: ではあるのですが、HeroCarouselの内部にsectionを持つより、利用側でsectionをもてた方が
- 見出しの自由度が上がる
- ページの構成を下記のように揃えられる
```
<section>
    <HeroCarousel />
</section>
<section>...</section>
<section>...</section>
```
などなどがあるかな〜と思ったので後者にしました！ -> https://github.com/openameba/spindle/pull/348/commits/6cecebe6c5eb09e9ecb8c48b79da702976c61622

2022-02-18 01:21 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.stories.mdx
> +export const carouselList = [
諸々追加しつつ、:k::ya_: 先生を見習って
- このコンポーネントでやっていること
- 利用時に注意してほしいこと

も追加しました！ -> https://github.com/openameba/spindle/pull/348/commits/87ab6f1640ee41489d9b9f94efd83023fa3d867d

2022-02-18 01:22 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.tsx
> +            <img
今回はlazyなしにしました！ 🙏🏻

2022-02-18 02:12 UTC, takami-shunsuke commented on packages/spindle-ui/src/HeroCarousel/hooks/useAutoPlayCarousel.ts
> +    document.body.addEventListener('touchend', onTouchEnd);
こちら元の実装意図としてはカルーセルUIの外でもスライドアクションの終了を検知できるように body に貼っていました（縦方向にも大きくスライドした場合の対応として）。

改めて見るとカルーセルアイテムの表示領域（ここでは `HeroCarousel` の `section` あたり）に貼ってしまっても良い気がしました（カルーセルアイテムのサイズが比較的大きく、スライドを検知する領域は十分確保できるかと思いました）。

2022-02-18 03:55 UTC, tokimari commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.tsx
> +      <section
追加で、昨日口頭で話しまして、h1やh2などのモジュールの見出しも、利用側で定義する方がより汎用性が高まると考え除外しました:pray:
（sectionのような文書構造をcomponentに持たせないなら、h1,h2も持たせるべきでないと判断）利用側が都度気にする必要はありますが・・！

2022-02-18 05:53 UTC, tokimari commented on packages/spindle-ui/src/HeroCarousel/hooks/useAutoPlayCarousel.ts
> +    document.body.addEventListener('touchend', onTouchEnd);
なるほど、検知目的で敢えてだったのですね！
そして今思えば、HeroCarousel範囲内でmousemoveしはじめ、HeroCarousel外でmouseupした時など（touchも同様）に検知できなくなるので、bodyに貼る方が良いかもしれません・・！:pray::pray:

2022-02-18 05:55 UTC, tokimari commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
> +  width: 18px;
ありがとう！すごくいい感じになったと思います！ 😄 :tada:

2022-02-18 06:30 UTC, tokimari approved these changes
残件issueについて了解です！小さく進めていきましょう 😄 :+1:
１件だけ質問書きましたがこのままでも問題はないかと思います！

2022-02-18 06:30 UTC, tokimari commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
> +  height: 11.6em;
ref: https://github.com/openameba/spindle/pull/348#discussion_r809601781

あくまで文字・アイコンのサイズだけ反映されれば良いので、carouselの高さを変える必要まではないかなーと昨日話していたと思いますが、ここも変えちゃうで良さそうです？（carouselコンテナの高さが変わることで不具合などなければ、私としては問題はないです！w）

2022-02-18 06:49 UTC, tokimari requested changes
https://github.com/openameba/spindle/runs/5241328702?check_suite_focus=true
bundlesizeのerrorがでてました:innocent:
大きなcomponentなのでcomponent単位でbugget上げるのはやむなしかなと思いつつ、、ちと確認お願いします！:bow:

2022-02-18 07:16 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
> +  height: 11.6em;
[テキスト & ボタンだけが大きくなるように実装した](https://github.com/openameba/spindle/pull/348/commits/5ab9465ed684b8debb60fe1f99945ae94be6447a)最初は実装したのですが、文字サイズ拡大した時に(文字に対してカルーセルが小さくて)違和感を感じてしまい、高さも対応しました 🙏🏻

2022-02-18 07:19 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
> +  height: 11.6em;
(文字サイズを拡大しなければ、px指定していた時と同じサイズです)

2022-02-18 11:43 UTC, herablog commented
あーごみん！あとで解消しておくます！

2022-02-18 11:47 UTC, herablog commented
@itsminadesu あと皆さんの :approve:  でたらコミットおまとめしたいので(CHANGELOG用でもあり)、マージお待ちください！

やりたいことは以下ですが、難しそうであればワイやっちゃいますです。

- fixupし1つの `feat(spindle-ui): heroCarouselを追加` にする
- [Co-authored-by追加](https://docs.github.com/ja/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) :takamin: と :k::ya_: さん追加しましょう

2022-02-21 00:58 UTC, takami-shunsuke commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
> +/* stylelint-disable plugin/selector-bem-pattern */
```suggestion
```
[nits] ここのコメントだけ消し忘れ？の気がするため、削除いただけると！私としては他は良さそうです！

2022-02-21 01:27 UTC, itsminadesu commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
> +/* stylelint-disable plugin/selector-bem-pattern */
ここは直接svgにスタイル当ててる関係で`stylelint-disable`しないとlinterで`Invalid component selector ".spui-HeroCarousel-control > svg"   plugin/selector-bem-pattern`と怒られてしまうため記載しています！ 🙏🏻

2022-02-21 01:34 UTC, takami-shunsuke commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
> +/* stylelint-disable plugin/selector-bem-pattern */
なるほど…すみませんそちら確かにでした🙏

2022-02-21 01:38 UTC, takami-shunsuke approved these changes
今後の進め方含め、良さそうです🙏 :spindle: :tatsujin:

2022-02-21 02:09 UTC, herablog commented on packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
> +/* stylelint-disable plugin/selector-bem-pattern */
いちおアイコンは`className`渡せるので指定してもいいかもですが、まぁどちらでもという感じです！

https://github.com/openameba/spindle/blob/4eda277842a477c7b1c9e0bdc5425aef0afec48f/packages/spindle-ui/src/Icon/Abematv.tsx#L11

2022-02-21 02:21 UTC, itsminadesu commented
@tokimari changed requestedの件修正されていると思いますので確認お願いいたします 🙇🏻 
@herablog commitまとめ & co-authored-by追加しました！

2022-02-21 02:31 UTC, herablog commented
おお、できてそう！

<img width="441" alt="" src="https://user-images.githubusercontent.com/869023/154879437-c6793ef3-9067-468c-9f5b-e180eb679d2d.png">

2022-02-21 02:32 UTC, tokimari approved these changes
ついにCarouselが！！！！！:tada:

2022-02-21 02:35 UTC, herablog approved these changes
:dokidoki:

2022-02-21 02:37 UTC, keiya01 approved these changes
:waiwai:

2022-02-21 04:37 UTC, merged