feat(spindle-ui): add pagination component
openameba/spindle pull request #440
Opened 2022-07-01 05:51 UTC by yasuda-shin

### 概要
ページ間の移動を目的として使用されることを想定したページネーションを追加しました。

### デザイン
<img width="593" alt="スクリーンショット 2022-07-01 14 50 28" src="https://user-images.githubusercontent.com/80251820/176832070-83f40616-7b38-437e-9d52-f7eb2c2e5409.png">

### パターン
- 現在のページが**1**でページ総数も**1**の場合
- 現在のページが**1**でページ総数が**2**以上ある場合
- 現在のページとページ総数が**同じ**場合
- currntに対して前後いくつのページ番号を表示するかはpageItems（**3** or **5**）で指定することができる default値は**3** に加えて上記のパターンを考慮する

### Props
- current: number;（現在のページ）
- total: number;（ページ総数）
- pageItems?: number;（ページ数の表示個数 3 or 5）
- pageCount?: boolean;（現在のページ数と総ページ数のカウントを表示するか否か）
- pagePrevNext?: boolean;（前へ次へアイコンを表示するか否か）
- pageFirstLast?: boolean;（最初へ最後へアイコンを表示するか否か）
- onClick?: (pageNumber) => void;
    - ページ番号をクリックした際はそのページ番号を返却
    - 「前へ」ボタンクリック時はcurrnt - 1を返却
    - 「次へ」ボタンクリック時はcurrnt + 1を返却
    - 「最初へ」ボタンクリック時は1を返却
    - 「最後へ」ボタンクリック時はtotal（ページ総数）を返却

2022-07-07 13:09 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +      className={[BLOCK_NAME, className].join(' ').trim()}
q. className受付OKですか？(スタイル調整したい場合はdivで囲って使ってね的なのがSpindleは多い印象でした)

2022-07-07 13:10 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +  onClick: (pageNumber: any) => void;
nits. 数字受けるってわかってるならばnumberでよさそうですかね？
```suggestion
  onClick: (pageNumber: number) => void;
```

2022-07-07 13:12 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +      className={[BLOCK_NAME, className].join(' ').trim()}
nits. あと `.filter(Boolean)` かましてるところもありそう？

2022-07-07 13:14 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +          if (item === null) {
nits. 先に pageViewItems.filter(item => item) してもよさそう

2022-07-07 13:15 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +    if (pageItems === 3) {
nits. マジックナンバーになりそうなもの、定数定義してもよさそうだなー

2022-07-08 06:31 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +  const pageViewItems = [...Array(pageItems)].map((_, i) => {
imo. 適当にまとめてみたやつ
```ts
const pageViewItems: number[] = []; // 表示すべき数字が入ってる配列
  // 表示数よりアイテム数が少ない時
  if (total <= pageItems) {
    Array.from({ length: total }).forEach((_, index) =>
      pageViewItems.push(index + 1)
    );
  } else if (pageItems === 3) {
    pageViewItems.push(1); // 1は必ず入る
    if (current === 1) {
      pageViewItems.push(2); // 現在値が1なら"1,2,total"になる
    } else if (current !== total) {
      pageViewItems.push(current); // "1,current,total"になる
    } else {
      pageViewItems.push(total - 1); // 現在値最大値なら"1,total-1,total"になる
    }
    pageViewItems.push(total); // 最後は必ず入る
  } else if (pageItems === 5) {
    pageViewItems.push(1); // 1は必ず入る
    if (current === 1 || current === 2) {
      pageViewItems.push(2); // 現在値が1か2なら"1,2,3,4,total"になる
      pageViewItems.push(3);
      pageViewItems.push(4);
    } else if (current !== total && current !== total - 1) {
      pageViewItems.push(current - 1); // "1,current-1,current,current+1total"になる
      pageViewItems.push(current);
      pageViewItems.push(current + 1);
    } else {
      pageViewItems.push(total - 3); // 現在値最大値なら"1,total-3,total-2,total-1,total"になる
      pageViewItems.push(total - 2);
      pageViewItems.push(total - 1);
    }
    pageViewItems.push(total); // 最後は必ず入る
  }

  // TODO: 3桁の時は表示しない仕様？
  const viewPrevHorizotal = total > pageItems && 2 < pageViewItems[1]; // totalは表示数超えてる前提で、前から2つ目のアイテムが2より大きいかどうか(最初が連続した数字じゃないことのチェック)
  const viewNextHorizotal =
    total > pageItems && pageViewItems[pageItems - 2] < total - 1; // totalは表示数超えてる前提で、後ろから2つ目のアイテムがtotal-1より小さいか(最後が連続した数字じゃないことのチェック)
```
```tsx
{pageViewItems.map((item, index) => (
          <li
            className={styles[`${BLOCK_NAME}-item`]}
            key={`pagination-item-${index}`}
          >
            {index === pageItems - 1 && viewNextHorizotal && (
              <MenuHorizotal
                aria-hidden="true"
                className={styles[`${BLOCK_NAME}-horizotal`]}
              />
            )}
            <button
              type="button"
              className={styles[`${BLOCK_NAME}-button`]}
              aria-current={current === item ? 'page' : undefined}
              aria-label={
                current === item
                  ? `${item}ページ目、現在のページ`
                  : `${item}ページ目`
              }
              onClick={() => handleOnClick(item)}
            >
              {item}
            </button>
            {index === 0 && viewPrevHorizotal && (
              <MenuHorizotal
                aria-hidden="true"
                className={styles[`${BLOCK_NAME}-horizotal`]}
              />
            )}
          </li>
        ))}
```

2022-07-08 06:31 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +  const pageViewItems = [...Array(pageItems)].map((_, i) => {
imo. 事前の計算は頑張るとして、表示時はロジックあんまり書きたくないな方針

2022-07-08 08:08 UTC, ta9yu commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +              current !== total)
[ココ](https://github.com/openameba/spindle/pull/440/files#diff-0413a8895a7295898d7b0ae6eebfac7cec39b0cde6d8efcc06da3b85c2b36d43R232-R237)と同じように変数にまとめちゃっても良さそうかなと思いました！

2022-07-08 08:08 UTC, ta9yu commented on packages/spindle-ui/src/Pagination/Pagination.css
> +    background-color: var(--gray-20-alpha);
```suggestion
    background-color: var(--color-surface-quaternary);
```
`--color-surface-quaternary` にしても良さそうですかね〜。

2022-07-08 08:08 UTC, ta9yu commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +                iconLabel ? 'has-label' : '',
ここのclass名ってcss側に定義されてなさそうですかね？

2022-07-11 08:28 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +      className={[BLOCK_NAME, className].join(' ').trim()}
受付OKにしていて `.filter(Boolean)` にしようかと思いますー。

2022-07-14 04:57 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +                <MenuHorizotal
q. 自分でやっといてあれなんですが、"..."が1つのli内に含まっちゃうのは許容で大丈夫そうですかね？(個別のliにする方法は思いついてないけど)

2022-07-14 04:57 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/Pagination.css
> +.spui-Pagination-item .spui-Pagination-button[aria-current] {
q. 数字のボタン部分にしかitemクラスが付いていないので、"<"等には指定したfocusのスタイルが効いてなさそうです。大丈夫ですか？

2022-07-14 04:57 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/Pagination.stories.mdx
> +## Normal
nits. おそらくまだ確認用かとは思いますが、ラベルありのstoryもあると嬉しいなと思いました

2022-07-14 05:00 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +                <MenuHorizotal
個別のliにいれると逆に読み上げで一個のリストとして扱われちゃうから今の状態でよきかなーという感じです。

2022-07-14 05:01 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +                <MenuHorizotal
なるほどー、良かったです◎

2022-07-14 08:55 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/Pagination.css
> +.spui-Pagination-icon {
📝 `box-sizing: border-box;` **以外**の指定を明示的にしておいてもらわないとダメかもしれない・・・

2022-07-14 09:03 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +                onClick={() => handleOnClick(item)}
q. こちらcurrentの場合もボタンは有効かつbuttonとしても活性でよかったでしょうか？雰囲気disabledっぽさを感じていたので。

2022-07-25 06:54 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/Pagination.stories.mdx
> +      total={10000}
current と total 逆のようです

2022-07-25 09:16 UTC, takami-shunsuke commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +  };
```suggestion
  const handleOnClick = useCallback((pageNumber: number) => {
    typeof handleClick === 'function' && handleClick(pageNumber);
  }, []);
```

nits. propsとして渡していたり、随所で使用しているため`useCallback`を使用しても良いと思いました！
`PaginationNavigation`のpropsは以下のように置き換えられそうです

```diff
- handleButtonClick={(pageNumber) => handleOnClick(pageNumber)}
+ handleButtonClick={handleOnClick}
```

2022-07-25 09:16 UTC, takami-shunsuke commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +    total > pageItems && pageViewItems[pageItems - 2] < total - 1;
IMO. この定数の定義（計算）は`usePageViewItems`のロジックとして隠蔽しても良さそうと思いました！

2022-07-26 01:17 UTC, keiya01 commented on packages/spindle-ui/src/Pagination/Pagination.stories.mdx
> +## currnt 8 total 20
```suggestion
## current 8 total 20
```
typoですかね？

2022-07-26 01:21 UTC, keiya01 commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +    typeof handleClick === 'function' && handleClick(pageNumber);
```suggestion
    handleClick && handleClick(pageNumber);
```
型でfunctionであることはわかるのでこれでも良いかもと思いました

2022-07-26 01:27 UTC, keiya01 commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +  handleClick: (pageNumber: number) => void;
`React.HTMLAttributes<HTMLElement>`を継承しているので`onClick`も推論されそうで、そうなると`handleClick`と混乱しそうなのでページネーションをハンドリングすることがわかる命名に変えた方がわかりやすい気がしました(良い名前思いついていないですが、、)
それかclassNameくらいしか使っていなそうなのでHTMLAttributeの継承をやめちゃって単純にonClick propsを生やすでも良さそうな気がしました

2022-07-26 01:31 UTC, keiya01 commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +              key={`pagination-item-${index}`}
```suggestion
              key={`pagination-item-${item}`}
```
itemを使っても良さそうな気がしました

2022-07-26 01:33 UTC, keiya01 commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +                    ? `${item}ページ目、現在のページ`
Q この辺詳しくないので質問ですが、`現在のページ`という文言はaria-currentと競合しそうだなと思ったのですが必要そうでしょうか:eyes:

2022-07-26 01:42 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +              <button
Q: そいえばですが、`<a href=hoge>`でのユースケースはなさそう or このコンポーネントでは考慮しないですかな

2022-07-26 01:54 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +interface Props extends React.HTMLAttributes<HTMLElement> {
PRの説明も最新に更新お願いしたいっす！

2022-07-26 01:57 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +  isPagePrevNext?: boolean;
まだ決まってなかったのですが、表示非表示系は名称できる限り合わせていこうと思うので何卒お願いします〜。

https://github.com/openameba/spindle/pull/482#discussion_r925160511

2022-07-26 02:03 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +  handleClick: (pageNumber: number) => void;
Paginationの機能としては変更・更新(change)くらいのニュアンスもありえそうだね

2022-07-26 02:09 UTC, herablog commented on packages/spindle-ui/src/Pagination/PaginationNavigation.tsx
> +        label = '最初へ';
IMO: ラベルは利用時のコンテキストによって変わりうるので、上書きできるようにしておいてもいいかなとおもいつつ、必要になってからでいいかもしれないです

2022-07-26 07:13 UTC, takami-shunsuke commented on packages/spindle-ui/src/Pagination/PaginationNavigation.tsx
> +  type: string;
```suggestion
  type: 'first' | 'last' | 'next' | 'prev';
```
nits. リテラルにできそうです！このコンポーネント内部でもswitchがType Guardとなり推論が改善されそうです

2022-07-27 06:06 UTC, yasuda-shin reviewed
ご指摘いただいた箇所諸々修正してみました〜。

2022-07-27 09:11 UTC, keiya01 commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +  handleClick: (pageNumber: number) => void;
それだと`onPagination`とかでも良いかもですかね:eyes:

2022-07-28 00:57 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +  handleClick: (pageNumber: number) => void;
`onPagination ` でいきますか。

2022-07-28 01:15 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +  handleClick: (pageNumber: number) => void;
`Pagination#onPagination` だと何が起こったかわかりにくいので、アクション名が欲しいすね。

2022-07-28 01:25 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +  handleClick: (pageNumber: number) => void;
一般的な`onChange`か`onPageChange` あたりが良さそうです。

https://ant.design/components/pagination/#API
https://atlassian.design/components/pagination/code
https://baseweb.design/components/pagination/
https://baseweb.design/components/pagination/

2022-07-28 01:36 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.css
> +.spui-Pagination-item .spui-Pagination-button:focus {
Q: こちらは`:focus-visible`にしていないのは意図的ですかな

2022-07-28 01:41 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.stories.mdx
> +</Preview>
コード固まってきてからでもよいので、他コンポーネントと同様にサンプルコードの表示もお願いします。

2022-07-28 01:43 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +interface Props extends React.HTMLAttributes<HTMLElement> {
`React.HTMLAttributes<HTMLElement>` 受け取ってもほとんど使っていないようなので、継承せずprops定義にしてよさそうです。

https://github.com/openameba/spindle/pull/440#discussion_r929445197

2022-07-28 01:51 UTC, herablog commented on packages/spindle-ui/src/Pagination/PaginationNavigation.tsx
> +  handleButtonClick: (pageNumber: number) => void;
こちらも `onX` で受け取りたいですね。

2022-07-28 01:53 UTC, herablog commented on packages/spindle-ui/src/Pagination/hooks/usePageViewItems.ts
> +export function usePageViewItems({ current, total, pageItems }: Payload) {
テスト追加しておきましょうか。

2022-07-28 01:56 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +                onClick={() => handleOnClick(item)}
@MasatoHonda にも確認しておきましょうか (確認済みであれば大丈夫です)

2022-07-28 01:59 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +                aria-label={`${item}ページ目`}
`nav[aria-label="ページネーション"]`の文脈でたどっているのと、textnodeに数値入っているので、特別指定せず表示と同程度の情報でいいかなと思いますがどうでしょう。

2022-07-28 02:04 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +export const Pagination = (props: Props) => {
テストの追加お願いします〜。見た目はVRTで担保できそうなのでインタラクティブなテストだけ追加で良さそうです。

このコンポーネントの場合、[Button](https://github.com/openameba/spindle/tree/main/packages/spindle-ui/src/Button)が参考になりそうです。

2022-07-28 02:06 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +    viewPrevHorizotal,
こちらも表示非表示で使っている場合は、`show*`にしておいていいかもです。

2022-07-28 02:41 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.css
> +  .spui-Pagination-item:nth-child(4),
:naruho:

2022-07-29 01:23 UTC, yasuda-shin reviewed
ご指摘いただいたpropsの名前やテストに関しては修正してみました。
ちょっと要件が変わりそうなのでレビューできるタイミングで再度コメントなりをしようと思います。

2022-07-29 01:23 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +export const Pagination = (props: Props) => {
ありがとございますー。
testing libraryはじめて書いたのですが
https://github.com/openameba/spindle/pull/440/commits/f616fc97096e5e007288f94d7f52cb15fca79948#diff-23223467fae42815ab65b9d42495a5831b50c40b39b783119a135a28606ff543R22-R23
インタラクティブなテストだけだとPaginationのclickに対してでいいのかなーというのがありつつ☝️の感じでほんとにテストできてるのですかね？
という疑問ありつつw
ドキュメント見てみたんですがいまいちどこ参照すればいいかわからずで聞いてしまいました！

2022-08-02 02:26 UTC, yasuda-shin commented
https://github.com/openameba/spindle/pull/440/commits/4a9be0b256389bd7a5b2501d9887c606a7f8402d

方針が変わりまして、☝️のように修正しました。
大まかに言いますと今まではbuttonを使用していた箇所をa要素（リンク）にする形にしました。
それに伴いリンクの遷移はclickのcallbackを想定したいたものをPaginationのコンポーネント内で提供するよう合わせて変更しています。

一点悩んでいて、a要素（リンク）をPaginationコンポーネントで提供する場合、`<Link>`あたりのroute処理も考慮する必要がありそうかもと思いつつ今までspindle-uiで同様の要件ってあったりしましたでしょうか？
探してみたものの見つからずでもし知見ありましたら。

再レビューみたいな形になってしまうのですが何卒ですー。

2022-08-02 03:07 UTC, sakito426 commented
>a要素（リンク）をPaginationコンポーネントで提供する場合、<Link>あたりのroute処理も考慮する必要がありそうかもと思いつつ

考慮されると大変ありがたいです:pray:(現状onClickでrouter.pushする想定だった為)

2022-08-02 03:08 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/PaginationNavigation.tsx
> +          onClick={() => onButtonClick(pageNumber)}
nits. disabledの時は発火しなくてよいかもです

2022-08-02 03:08 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/PaginationNavigation.tsx
> +        pageNumber = current - 1;
q. (disabledなのでおそらく挙動に影響はないと思いつつ)currentが1の場合、下限突破して0になりそうですが問題ないですか？

2022-08-02 03:08 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/PaginationNavigation.tsx
> +        pageNumber = current + 1;
q. (disabledなのでおそらく挙動に影響はないと思いつつ)currentがtotalの場合、上限突破しそうですが問題ないですか？

2022-08-02 03:08 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/PaginationNavigation.tsx
> +              ? url.replace(/PAGA_NUMBER/g, pageNumber.toString())
q. 1ページ目ってpageを表すパラメータが省略可能だったりするケースがあると思っており、その際SEO的には省略URLと同じことを示せたらよい気がしたのですが、そのあたりは利用元がcanonical指定で頑張れ〜って感じでしょうか？

2022-08-02 03:12 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/Pagination.css
> +    display: none;
must. 画面幅に応じて要素が消えますが、単純に数字部分のみ消してしまうと要件に合わないような気がしました(1...3...5表示になるのが想定挙動かと思ったのですが意図通りですか？)
![image](https://user-images.githubusercontent.com/4308418/182283659-3019afbe-de90-4285-a593-643c0be3ebbf.png)

2022-08-02 05:22 UTC, yasuda-shin reviewed
> a要素（リンク）をPaginationコンポーネントで提供する場合、あたりのroute処理も考慮する必要がありそうかもと思いつつ
> 考慮されると大変ありがたい

これはまだどうやるか考え中（思いついてない）ので引き続きもくもくしてみます。

それ以外の箇所修正してみましたー。

2022-08-02 05:22 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/PaginationNavigation.tsx
> +              ? url.replace(/PAGA_NUMBER/g, pageNumber.toString())
`rel="canonical"` は想定していなくて1ページ目が省略可能の場合ってそもそも要望として`PAGA_NUMBER `つけないでOKみたいな感じだったりするんですかね？
どのようなurlを想定しているのだろうかとも思いつつ。

2022-08-02 05:25 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +  url: string;
あ、本当だ失礼しました💦 
そうですね、例があるとよりわかりやすそうです◎

2022-08-02 05:31 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/PaginationNavigation.tsx
> +              ? url.replace(/PAGA_NUMBER/g, pageNumber.toString())
https://ameblo.jp/shibuya/page-1.html の `<link rel="canonical" href="https://ameblo.jp/shibuya/">` などを想像していました
👆の場合は1ページ目へのページネーションリンクは https://ameblo.jp/shibuya/ で設定されてそうです
とは言えこれ、コンポーネント側で考慮するの難易度高かったですね:sorry:(ココで思考停止😇)

2022-08-02 05:33 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/Pagination.css
> +    display: none;
>「...」を出した方がいいという意図でしたかね？？

です(すみません:pray:

2022-08-02 05:49 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/util/url.ts
> +export function createUrl(url: string, pageNumber: string) {
nits. 変換元が第2引数をnumberからstringに変換しているようなので、ここではnumberを受け取って関数内でstringに変換してもよさそうだなと思いました
```suggestion
export function createUrl(url: string, pageNumber: number) {
```

2022-08-02 05:49 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/util/url.ts
> +export function createUrl(url: string, pageNumber: string) {
nits. 関数に切り出されたことでテスト欲しくなっちゃいますねｗ

- PAGA_NUMBER含まなかった時
- pageNumberが数値じゃない時

特に👆とかの場合どうハンドリングしましょうか？

2022-08-02 05:49 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +                onClick={() => handleOnClick(item)}
q. current===itemの時、hrefが無ければクリックイベントって発火はしないでしたっけ？(忘却
そうじゃなければナビゲーション同様にdisabled時にはundefinedにしてあげるとよさそうな気がしました

2022-08-02 07:22 UTC, herablog commented on packages/spindle-ui/src/Pagination/util/url.ts
> +export function createUrl(url: string, pageNumber: string) {
`PAGA` って `PAGE` ことかな

2022-08-02 07:34 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/util/url.ts
> +export function createUrl(url: string, pageNumber: string) {
www

2022-08-02 08:18 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/util/url.ts
> +export function createUrl(url: string, pageNumber: string) {
正しくはPAGUでしたね。すいません。

2022-08-02 08:18 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/util/url.ts
> +export function createUrl(url: string, pageNumber: string) {
テスト追加しては見たものの

> pageNumberが数値じゃない時

これって必須かつnumber指定してるのでstringだったりすると警告が出る気がするのですがその辺りのテストって可能なものなんでしょうか？
調べたんですがいまいちわからずでして。質問返しすいません。

2022-08-02 08:39 UTC, sakito426 commented on packages/spindle-ui/src/Pagination/util/url.ts
> +export function createUrl(url: string, pageNumber: string) {
あ、そうですねごめんなさい。
numberじゃない時〜は大丈夫か、調べる時間取らせちゃってすみません〜

2022-08-15 09:07 UTC, yasuda-shin commented
> a要素（リンク）をPaginationコンポーネントで提供する場合、あたりのroute処理も考慮する必要がありそうかもと思いつつ
考慮されると大変ありがたい

https://github.com/openameba/spindle/pull/440/commits/cc67c6c0dddcf11368986aaf5f9b4f809ab69e23

上記修正してみました。
docsに利用方法を追記しつつ`e.preventDefault();`で遷移のイベントを一度とめてもらいサービス側で任意のルーティングをしてもらう想定です。

2022-08-15 23:55 UTC, takami-shunsuke approved these changes

2022-08-15 23:55 UTC, takami-shunsuke commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +    onPagination && onPagination(event, pageNumber);
```suggestion
    onPagination?.(event, pageNumber);
```
IMO. こちらのように短く書くこともできそうです！

2022-08-15 23:56 UTC, takami-shunsuke requested changes
すみません、、１つ前コメントのつもりでした🙇‍♂️

2022-08-18 02:24 UTC, yasuda-shin commented
改めてデザイン確認をしていただく。

2022-08-18 03:52 UTC, keiya01 reviewed
すみません遅くなりました
気になったところコメントしました

2022-08-18 03:52 UTC, keiya01 commented on packages/spindle-ui/src/Pagination/Pagination.test.tsx
> +    expect(onClick).toBeCalled();
引数のpageNumberに正しく値が入っているかもチェックしても良さそうです

2022-08-18 03:52 UTC, keiya01 commented on packages/spindle-ui/src/Pagination/PaginationNavigation.tsx
> +          href={isDisabled ? undefined : createUrl(url, pageNumber)}
disabled属性を使わないのは理由ありますか?

2022-08-18 03:52 UTC, keiya01 commented on packages/spindle-ui/src/Pagination/hooks/useShowItems.test.ts
> +  it('should return show props is currnt first', () => {
```suggestion
  it('should return show props is current first', () => {
```

2022-08-18 03:52 UTC, keiya01 commented on packages/spindle-ui/src/Pagination/util/url.ts
> +  return url.replace(/PAGE_NUMBER/g, pageNumber.toString());
ここの`PAGE_NUMBER`のplaceholderは定数として切り出して、利用者側には定数を埋め込んでもらうようにした方がplaceholderを変えたいとなった時に楽そうだなと思ったりしました

それかそもそもURLの作成を利用者側に委ねちゃうのもありな気がしました
`createUrl`をpropsとして受け取るようにしちゃうイメージです

2022-08-18 04:00 UTC, herablog commented on packages/spindle-ui/src/Pagination/util/url.ts
> +  return url.replace(/PAGE_NUMBER/g, pageNumber.toString());
同じく後者パターンもありかなと思ってコメント忘れてましたｗ pageNumber渡して文字列返してもらう関数受け取って、指定されていなければ用意されたデフォルト関数が実行される感じでもいいかも

2022-08-18 08:33 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/util/url.ts
> +  return url.replace(/PAGE_NUMBER/g, pageNumber.toString());
https://github.com/openameba/spindle/pull/440/commits/5bc716cb7a34ea0c1d405910ba083db98c96964f
後者パターンで利用者側に関数渡してもらう感じにしてみたんですが☝️なイメージであってますかね？
storybookにも追加してみて任意のURL生成できそうよさそう。

2022-08-18 08:34 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/PaginationNavigation.tsx
> +          href={isDisabled ? undefined : createUrl(url, pageNumber)}
前はbuttonタグを利用してたんですが諸々考慮してaタグ（[アンカー要素](https://developer.mozilla.org/ja/docs/Web/HTML/Element/a)）に変更した影響でdisabledじゃなくしてます。aタグdisabled属性使えないという。

2022-08-22 08:21 UTC, ta9yu reviewed
遅くなりました 🙇‍♂️

2022-08-22 08:21 UTC, ta9yu commented on packages/spindle-ui/src/Pagination/Pagination.css
> +.spui-Pagination-link + .spui-Pagination-horizotal {
```suggestion
.spui-Pagination-horizontal + .spui-Pagination-link,
.spui-Pagination-link + .spui-Pagination-horizontal {
```
ここも細かいですが 🙇‍♂️

2022-08-22 08:21 UTC, ta9yu commented on packages/spindle-ui/src/Pagination/PaginationNavigation.tsx
> +    let iconElement;
`pageNumber` と同様に型の定義しておいたほうが良かったりしますかね。

2022-08-22 09:16 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/PaginationNavigation.tsx
> +    let iconElement;
最初そうしようかと思ったんですがそうするとiconのデフォルト値設定しなきゃで何がいんだろってなってやめたんですよね。

2022-08-22 09:36 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/Pagination.css
> +.spui-Pagination-link + .spui-Pagination-horizotal {
アイコン自体の修正は別でやるとしてclass名や変数名は修正しました！

2022-08-29 05:29 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/PaginationItem.tsx
> +        {type === 'next' && (
@herablog 
`first` と `last` の際は表示する必要がなくcssのorderで順序をいれかえるとちょっとややこしいかなと思い現状のままにしております。
デザイン確認時にその辺り含め相談してみるかもです。

2022-08-29 05:31 UTC, yasuda-shin commented
@herablog 
諸々修正したものpushしました。改めてご確認お願いしたくですー。

@takami-shunsuke @keiya01 
原さんとペアプロ的な感じで修正しつつご指摘いただいた箇所もなおっているかと思うのでご確認いただければとー。

2022-08-31 01:28 UTC, herablog commented on packages/spindle-ui/src/Pagination/PaginationItem.tsx
> +        {type === 'next' && (
ざっと見た感じアイコンは装飾扱いで要素の順番関係なさそうなので、やはりCSSで対応してみてもいいかなと思いますがどうでしょう。`<a>`にtypeのクラス名が付いてるのとflexboxっぽいので比較的容易かなと思いましたがどうですかな。

2022-08-31 04:11 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/PaginationItem.tsx
> +        {type === 'next' && (
https://github.com/openameba/spindle/pull/440/commits/107bd6d9c3ba3588780c4abcfbdf2f614fe5fb63
☝️修正してみましたー。

```
const isShowLabel = type === ('prev' || 'next');
```

だとうまく効かず。javascript難しい。

2022-08-31 09:17 UTC, herablog commented on packages/spindle-ui/src/Pagination/PaginationItem.tsx
> +  (prevProps, nextProps) => prevProps.type === nextProps.type,
Q: こりって`type`だけで大丈夫ですかね。(実際にあるかわかりませんが) current, totalなどほかprop依存の計算があるように見えるので、意図通りか気になりました。

2022-08-31 09:27 UTC, herablog commented on packages/spindle-ui/src/Pagination/PaginationItem.tsx
> +        {type === 'next' && (
IMO: ありがとうございます〜(アイテム数変更あったときの想定度合いは変わりそうですが)以下でもよさそうですが、結果は同じなのでどちらでも大丈夫です〜

```css
.spui-PaginationItem-link--prev {
  flex-direction: row-reverse;
}
```

2022-08-31 09:27 UTC, herablog commented on packages/spindle-ui/src/Pagination/PaginationItem.tsx
> +      type === ('first' || 'prev') ? current === 1 : current === total;
こり想定した動きになってますかな
ref: https://github.com/openameba/spindle/pull/440#discussion_r959144920

2022-09-01 05:27 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/PaginationItem.tsx
> +      type === ('first' || 'prev') ? current === 1 : current === total;
なっておらずですね。ご指摘ありがとうございます。
修正しました！

2022-09-01 10:53 UTC, takami-shunsuke reviewed
対応ありがとうございます！
細かいですが、改めて気になったところを挙げてみました🙏

2022-09-01 10:53 UTC, takami-shunsuke commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +      {...rest}
type の extends で `React.HTMLAttributes<HTMLElement>` の attributes をそのまま受け取っていますが、Storybookの方でも特に利用されていなそうで、カスタマイズの想定が特になさそうでしたら`className: string`だけを受け取る形で厳密にしても良さそうと思いました👀

ここの `rest` をなくして、extendsもなくす or Pick で className だけ使用するイメージです

2022-09-01 10:53 UTC, takami-shunsuke commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +              .trim()}
```suggestion
            className={`${BLOCK_NAME}-item ${BLOCK_NAME}-item--first`}>
```
条件分岐があるclassNameの場合に`filter(Boolean)`を通すために配列を用いていたかと思うのですが、そのようなパターンでなければ`join`を使わず、シンプルに文字列で良さそうと思いました（ほかの箇所も同様に）🙏

2022-09-01 10:53 UTC, takami-shunsuke commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +              </a>
```suggestion
            {current === pageNumber ? (
                <a
                  className={`${BLOCK_NAME}-link`}
                  aria-label={`${pageNumber}ページ目`}
                  aria-current="page"
                  aria-disabled
                >
                  {pageNumber}
                </a>
              ) : (
                <a
                  className={`${BLOCK_NAME}-link`}
                  aria-label={`${pageNumber}ページ目`}
                  href={createUrl(pageNumber)}
                  rel="nofollow"
                  onClick={(e) => {
                    handleOnClick(e, pageNumber);
                  }}
                >
                  {pageNumber}
                </a>
              )}
```
nits. 同じ比較の分岐が多いため、マークアップごと分岐するかattributeのオブジェクトをuseMemoで返して使うようにするなどの方が可読性も含めて良いかもと思いました👀

2022-09-01 10:53 UTC, takami-shunsuke commented on packages/spindle-ui/src/Pagination/hooks/useShowItem.ts
> +  const showItem = useMemo(() => {
```suggestion
  const displayItem = useMemo(() => {
```
IMO. 細かいのですが、boolean or functionの印象を受けるため（ほかの同じプレフィックスの定数がbooleanでもあり）、命名を変更しても良さそうと思いました🙏

2022-09-01 10:53 UTC, takami-shunsuke commented on packages/spindle-ui/src/Pagination/hooks/useItemPageNumber.ts
> +  }, [type, current, total]);
```suggestion
  }, [type, current, total, isDisabled]);
```
nits. こちらも必要そうです！

2022-09-01 10:53 UTC, takami-shunsuke commented on packages/spindle-ui/src/Pagination/hooks/useShowItem.test.ts
> +  it('should return show props is current first', () => {
nits. if current is end (`showNextHorizontal === false`となるパターン) のテストケースも追加いただくと良さそうです🙏

2022-09-02 00:54 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +      {...rest}
今はカスタマイズしてないのですが今後含めて拡張性持たせてもいいかもですねー。
という感じでペアプロしつつこの形にしたという経緯はありつつですー。

2022-09-02 00:55 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +              </a>
`current === pageNumber` と `current === pageNumber + 1` があって絶妙に分けづらいというのがありつつ。

https://github.com/openameba/spindle/pull/440/commits/81866bed7f093b0162248be1c8c3b0b8b01b9981#diff-0413a8895a7295898d7b0ae6eebfac7cec39b0cde6d8efcc06da3b85c2b36d43R82-R83

☝️変数にして気持ち見やすくなったかなーという感じなんですがどうですかねー。

2022-09-02 00:56 UTC, yasuda-shin commented
ご指摘いただいた箇所諸々修正してみました！

2022-09-02 02:10 UTC, takami-shunsuke commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +      {...rest}
なるほどです！それでしたら問題なさそうです🙏

2022-09-02 02:10 UTC, takami-shunsuke commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +              </a>
ありがとうございます！良さそうです！🙏

2022-09-02 02:12 UTC, takami-shunsuke approved these changes
修正ありがとうございます！
こちらだけ気になり、ほか問題なさそうです！

2022-09-02 02:12 UTC, takami-shunsuke commented on packages/spindle-ui/src/Pagination/PaginationItem.tsx
> +          .trim()}
別コメントと同様で、こちらも `.join` 以降無くして文字列にできそうです！

2022-09-02 05:51 UTC, herablog commented on packages/spindle-ui/src/Pagination/hooks/useShowItem.ts
> +  const displayItem = useMemo(() => {
こり、`item`に追加していってもいいですが、それぞれ配列で返しちゃってもよさそうですがどうでしょう。読みやすくコメントもなくてもわかるような (?) 最初と最後の値見するかもですがそりはテストで担保してもいいかも。

```TypeScript
const displayItem = useMemo(() => {
    if (current === 1 || current === 2) {
      return [1, 2, 3, 4, total];
    } else if (current !== total && current !== total - 1) {
      return [1, current - 1, current, current + 1, total];
    } else {
      return [1, total - 3, total - 2, total - 1, total];
    }
  }, [current, total]);
```

2022-09-02 07:21 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.test.tsx
> +          url.replace(/CURRENT/g, pageNumber.toString())
こちらの方が実際の利用イメージに近くよいかもです

```suggestion
          `/detail/${pageNumber}.html`
```

2022-09-02 07:31 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.tsx
> +  const handleOnClick = useCallback(
nits: `handleClick` の方がより一般的・適切かもです (大きな問題ではないですが)

```suggestion
  const handleClick = useCallback(
```

2022-09-05 05:58 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/hooks/useShowItem.ts
> +  const displayItem = useMemo(() => {
確かに。スッキリして良さそうです。
やはり初見ではわかりづらそうな気もするのでコメント残しつつ上記の配列返す形にしようかと思います。

2022-09-09 04:51 UTC, yasuda-shin commented
@herablog 
https://github.com/openameba/spindle/pull/440/commits/b72730d8b1d028613f5b8ed9b310b587660767fb
結果☝️のようにhover時のスタイルを修正しております。
こちらで諸々ご指摘いただいた箇所修正しつつデザイン確認も合わせてできたと思うので改めてご確認お願いしたく！

2022-10-04 09:54 UTC, sakito426 commented
|дﾟ)ﾁﾗｯ

2022-10-05 02:20 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.stories.mdx
> +![stability-wip](https://img.shields.io/badge/stability-work_in_progress-lightgrey.svg)
Q: このコンポーネントはこの後どうなるんでしたっけ？本番利用はしないですかね

https://github.com/openameba/spindle/tree/main/packages/spindle-ui#%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88%E4%B8%80%E8%A6%A7

2022-10-05 02:21 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.css
> +    display: none;
これは結果どうなったんでしたっけ...!?

2022-10-05 02:30 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.test.tsx
> +    expect(onClick).toBeCalled();
こりも残りコメントなのでいちお状況確認したいです〜

2022-10-05 04:28 UTC, yasuda-shin reviewed
ご指摘いただいた箇所修正したのと一部コメントお返事しておりますー。

2022-10-05 04:28 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/Pagination.css
> +    display: none;
デザイナーさん確認して結果、「...」を出す形になっております。

2022-10-05 04:28 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/Pagination.stories.mdx
> +![stability-wip](https://img.shields.io/badge/stability-work_in_progress-lightgrey.svg)
おそらくどこかのコンポーネントからコピペしたの残ってそうですね。
本番利用するので修正しました。ご指摘ありがとうございます！

2022-10-05 04:28 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/Pagination.test.tsx
> +    expect(onClick).toBeCalled();
https://github.com/openameba/spindle/pull/440/commits/045b05f6caf2ed2886e7e32f8fa2bd5cbecf160c#diff-23223467fae42815ab65b9d42495a5831b50c40b39b783119a135a28606ff543R26
上記でクリック時のpageNumber何かチェック追加しております。

2022-10-05 05:43 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.stories.mdx
> +<Source
Docsで`createUrl`の中身がうまく表示されてないかも

https://ameba-spindle--pr440-feat-pagination-hfjhf2fd.web.app/?path=/docs/pagination--normal

2022-10-05 06:47 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/Pagination.stories.mdx
> +<Source
https://github.com/openameba/spindle/pull/440/commits/98b2983b3331b790feede3d62219ee2b7a308477

<img width="1036" alt="スクリーンショット 2022-10-05 15 46 36" src="https://user-images.githubusercontent.com/80251820/193997806-9555f88b-b69e-4952-95c2-6306b1e5be69.png">
上記のような形に修正してみました。
どうでしょうか。

2022-10-05 07:02 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.stories.mdx
> +<Source
`Normal`は大丈夫そうです！それ以外も同様に変えていただけますか？

2022-10-05 07:09 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/Pagination.stories.mdx
> +<Source
スクリーンショットNormalのみで申し訳ですがhttps://github.com/openameba/spindle/commit/98b2983b3331b790feede3d62219ee2b7a308477
☝️他の部分も修正しております。

2022-10-05 07:25 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.stories.mdx
> +  code={'<Pagination total={999} current={900} showCount={true} showPrevNext={true} showFirstLast={true} createUrl={(pageNumber) => /detail/{pageNumber}.html} />'}
```suggestion
  code={'<Pagination total={999} current={900} showCount={true} showPrevNext={true} showFirstLast={true} createUrl={(pageNumber) => `/detail/${pageNumber}.html`} />'}
```

2022-10-05 07:25 UTC, herablog commented on packages/spindle-ui/src/Pagination/Pagination.stories.mdx
> +<Source
https://github.com/openameba/spindle/pull/440/files#r987608786 かにゃ？

2022-10-05 07:31 UTC, yasuda-shin commented on packages/spindle-ui/src/Pagination/Pagination.stories.mdx
> +<Source
あれ。大変失礼しました。修正してみました！

2022-10-06 06:46 UTC, yasuda-shin commented
コミットまとめつつforce pushしましたー。

2022-10-06 06:47 UTC, herablog commented
|дﾟ)ﾁﾗｯ

2022-10-06 06:56 UTC, yasuda-shin commented
|дﾟ)ﾁﾗｯ

2022-10-06 06:58 UTC, herablog approved these changes
ﾄﾞ━━━━━━(ﾟДﾟ)━━━━━━ﾝ!!!

2022-10-11 10:40 UTC, merged