fix: dialogのpositionを画面中央に固定
openameba/spindle pull request #719
Opened 2023-05-17 16:53 UTC by lanberb

## 概要
Dialog Componentの表示位置がスクロール位置に追従していないので修正しました。

| 変更前 | 変更後 |
| --- | --- |
| <video src="https://github.com/openameba/spindle/assets/57176655/b45381f6-164f-43a2-8883-128f10c5299d"/> | <video src="https://github.com/openameba/spindle/assets/57176655/690ff736-0b45-490f-99c5-a7eb26943bfa"/> |

2023-05-17 16:55 UTC, lanberb commented on packages/spindle-ui/src/Dialog/Dialog.tsx
> +}: React.ComponentProps<'div'> & PartsProps) => {
ここら辺の型はSemiModal, AppealModalのもの(L189部分)を流用しました。

https://github.com/openameba/spindle/blob/6a7ca2a54919149e39d284457d72975a440ebc1b/packages/spindle-ui/src/Modal/SemiModal.tsx#L183-L191

2023-05-18 02:38 UTC, itsminadesu commented
！？！？？！？！？（プロSpindlerだ... :kami:）

2023-05-18 03:04 UTC, itsminadesu approved these changes
ありがとうすぎる！！！ 🎉
「これがOSSか...」とherablogさんとｷｬｯｷｬしてしまいました 😄 笑笑

![今日はもう終わりだからパソコン落としといてね](https://github.com/openameba/spindle/assets/42470015/92dda181-a523-4224-8f9e-9b2fa4d25df0)

2023-05-18 03:10 UTC, herablog commented
user agent stylesheetでfixedなはずなんだけどな〜と思ったら、polyfillで上書きされてるのか〜
<img width="411" alt="Screenshot 2023-05-18 at 12 09 33" src="https://github.com/openameba/spindle/assets/869023/2d94dce0-1b8b-4e5d-95d1-584d0fbca8bf">

2023-05-18 03:28 UTC, herablog commented on packages/spindle-ui/src/Dialog/DialogExample.tsx
> +    <Dialog.StyleOnly style={{ position: 'relative' }}>
thinking: `<Dialog.StyleOnly>` は `<ReactModal><Dialog.StyleOnly>...</Dialog.StyleOnly></ReactModal>` みたいな使い方を想定しているので、fixed入っちゃって大丈夫か気になり中です

2023-05-18 03:54 UTC, itsminadesu commented on packages/spindle-ui/src/Dialog/DialogExample.tsx
> +    <Dialog.StyleOnly style={{ position: 'relative' }}>
確かにそうですね... 今回の修正対象は通常利用の場合のみなので、

- 通常利用の場合： （DialogPolyfillでpositionが上書きされてしまうので）本PRの変更通り、 `spui-Dialog` に `fixed` つけるようにしてバグ修正する
- StyleOnly利用の場合： （利用側で上書いてもらうのではなく）StyleOnlyに追加で `${BLOCK_NAME}--styleOnly` クラス的なのを渡して、 `.spui-Dialog--styleOnly { position: static; }`で初期化する

などすればStyleOnlyユーザーにも影響ないかなと思いました 💭 （StyleOnlyにはclassNameが渡せるようになっているので、利用側が他のpositionを当てたい場合でも上書くことはできる）

2023-05-18 04:15 UTC, herablog commented on packages/spindle-ui/src/Dialog/DialogExample.tsx
> +    <Dialog.StyleOnly style={{ position: 'relative' }}>
:yoshi:

2023-05-18 06:44 UTC, itsminadesu commented on packages/spindle-ui/src/Dialog/DialogExample.tsx
> +    <Dialog.StyleOnly style={{ position: 'relative' }}>
> （利用側で上書いてもらうのではなく）StyleOnlyに追加で ${BLOCK_NAME}--styleOnly クラス的なのを渡して、 .spui-Dialog--styleOnly { position: static; }でspui-Dialogのfixedを上書きする（初期化する）

ちなみにこれは、下記に`${BLOCK_NAME}--styleOnly`クラスを追加する + [Dialog.css](https://github.com/openameba/spindle/blob/main/packages/spindle-ui/src/Dialog/Dialog.css)に`.spui-Dialog--styleOnly { position: static; }`を追加する、という意です！ 🙏🏻 

https://github.com/openameba/spindle/blob/6a7ca2a54919149e39d284457d72975a440ebc1b/packages/spindle-ui/src/Dialog/Dialog.tsx#L124

2023-05-23 07:33 UTC, herablog requested changes
わかりやすいようにステータス変更しやす
https://github.com/openameba/spindle/pull/719#discussion_r1197457534

2023-06-28 07:54 UTC, itsminadesu commented
@herablog @lanberb 
施策内でDialogを使うので、こちら巻き取ります！ 🙏🏻

2023-08-29 12:48 UTC, itsminadesu commented on packages/spindle-ui/src/Dialog/DialogExample.tsx
> +    <Dialog.StyleOnly style={{ position: 'relative' }}>
@herablog こちら私の方で巻き取って修正済みです :nanitozo:

2023-08-30 00:52 UTC, herablog commented on packages/spindle-ui/src/Dialog/DialogExample.tsx
> +    <Dialog.StyleOnly style={{ position: 'relative' }}>
@itsminadesu ありがとうございます！ちとVRT動かしたいのでmainの最新を取り込んでpushもお願いしたいです！

2023-08-30 05:09 UTC, itsminadesu commented on packages/spindle-ui/src/Dialog/DialogExample.tsx
> +    <Dialog.StyleOnly style={{ position: 'relative' }}>
動いて...？

2023-08-30 05:16 UTC, herablog commented on packages/spindle-ui/src/Dialog/DialogExample.tsx
> +    <Dialog.StyleOnly style={{ position: 'relative' }}>
skipped...!?

2023-08-30 05:16 UTC, herablog commented on packages/spindle-ui/src/Dialog/DialogExample.tsx
> +    <Dialog.StyleOnly style={{ position: 'relative' }}>
:skipping:

2023-09-01 11:32 UTC, itsminadesu commented on packages/spindle-ui/src/Dialog/DialogExample.tsx
> +    <Dialog.StyleOnly style={{ position: 'relative' }}>
@herablog re-runしてもskippedしちゃっていそうですが、一旦本PRに関しては :yoshi: しちゃいます...？ 🤔

2023-09-01 11:34 UTC, herablog commented on packages/spindle-ui/src/Dialog/DialogExample.tsx
> +    <Dialog.StyleOnly style={{ position: 'relative' }}>
`workflow_dispatch` で動くと思うので、こりPRはそりで確認しましょか。
https://github.com/openameba/spindle/blob/400fcc89810162a6fb4b9c99802e85dc87d9e86e/.github/workflows/visual-regression-test.yml#L10

2023-09-20 01:27 UTC, itsminadesu commented on packages/spindle-ui/src/Dialog/DialogExample.tsx
> +    <Dialog.StyleOnly style={{ position: 'relative' }}>
Skipped解消され動きました 🎉

2023-09-20 01:28 UTC, itsminadesu approved these changes

2023-09-20 01:29 UTC, herablog approved these changes
![エンジニアを褒めるネコ:自宅作業します](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/26_%E8%87%AA%E5%AE%85%E4%BD%9C%E6%A5%AD%E3%81%97%E3%81%BE%E3%81%99.png)

2023-09-20 01:46 UTC, merged