fix(spindle-ui): button size & weight
openameba/spindle pull request #91
Opened 2020-11-06 10:13 UTC by hiloki

Buttonのサイズと太さがドキュメントと合っていなかったため修正。
ref: https://spindle.ameba.design/57edc1abc/p/89add9-button/b/1952d0

`font-family` はglobalに指定されるであろう Spindle標準の指定を継承する前提にした。

2020-11-06 10:45 UTC, herablog requested changes
すまそんがlintエラー対応おねしゃす！

https://github.com/openameba/spindle/pull/91/checks?check_run_id=1363091295

yarn formatでいけそうな気がします。

2020-11-06 10:45 UTC, herablog commented
あとなぜかコンフリクト？

2020-11-06 10:52 UTC, MasatoHonda approved these changes
見た目大丈夫そうでした〜

2020-11-09 00:25 UTC, herablog approved these changes
ありがトン！

2020-11-09 01:19 UTC, merged